import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));

const FAILURE = {
  normal_empty: "A successful command with no match, no rows, or no device is an empty observation; save it as empty and do not turn it into a failure.",
  model_correctable: "For an invalid path, option, format, or query, read stderr, correct the input, and retry with a new command and recorded revision.",
  transient_retryable: "For a busy process, temporary network error, or service startup race, retain logs and retry within the job budget after checking for duplicate side effects.",
  missing_condition: "If a required file, device, authorization, service, network permission, or architecture is absent, record inconclusive/needs_human with the missing condition.",
  permanent: "For unsupported input, corrupt artifacts, an unavailable binary, or an unrecoverable exit, stop and record permanent_failure with stderr and the exact command."
};

const entry = (imageKey, spec) => ({
  image_key: imageKey,
  id: spec.id,
  kind: spec.kind ?? "tool",
  agent_visible: spec.agent_visible ?? !spec.implementation_only,
  implementation_only: spec.implementation_only ?? false,
  version: spec.version ?? "unspecified",
  version_source: spec.version_source ?? "source inventory requires confirmation",
  commands: spec.commands ?? [],
  usage_scenario: spec.usage_scenario ?? "Use this entry only when its input and required runtime context match the task.",
  selection_basis: spec.selection_basis ?? "Choose it after checking the image manifest and input type; do not substitute a tool with a different evidence model.",
  prerequisites: spec.prerequisites ?? ["Read the frozen job image manifest and work under the job workspace."],
  minimal_invocation: spec.minimal_invocation ?? "Run the command with an explicit input and output location.",
  common_parameters: spec.common_parameters ?? ["--help", "explicit input path", "explicit output path"],
  output_interpretation: spec.output_interpretation ?? "Treat stdout/stderr and exit code as observations. A successful process does not prove a security conclusion by itself.",
  failure_handling: { ...FAILURE, ...(spec.failure_handling ?? {}) },
  composition_flow: spec.composition_flow ?? "Save the raw output, normalize only with a documented transformation, then pass the artifact to the next tool or verifier.",
  evidence_retention: spec.evidence_retention ?? ["Exact command and arguments", "image key and digest", "tool version", "stdout/stderr", "exit code", "input and output hashes"],
  version_limits_side_effects_cleanup: spec.version_limits_side_effects_cleanup ?? "Version is bound to the image manifest. Use a workspace-local output directory, bound resources, and remove temporary files after evidence is retained.",
  verification_status: spec.verification_status ?? "source_declared_unexecuted",
  verification_note: spec.verification_note ?? "Entry is derived from the pinned source manifest; this catalog run did not build or execute the image.",
  ...(spec.device_required === undefined ? {} : { device_required: spec.device_required }),
  ...(spec.requires_egress === undefined ? {} : { requires_egress: spec.requires_egress }),
  ...(spec.covers === undefined ? {} : { covers: spec.covers })
});

const baseApt = [
  ["git", "1:2.39.5-0+deb12u3", ["git"], "Inspect or update a checked-out source tree and preserve commit provenance.", "Use git for repository state and history; use rg for content search and a language tool for semantic analysis.", "git status --short", ["--status", "--diff", "--show-toplevel"]],
  ["python3", "3.11.2-1+b1", ["python3"], "Run small deterministic transforms or inspect structured artifacts when no specialized tool is needed.", "Use an image-provided Python runtime for glue logic; use uv or managed Python versions in Kali when a project dependency requires them.", "python3 -c 'print(40 + 2)'", ["-c", "script path", "input/output paths"]],
  ["curl", "7.88.1-10+deb12u15", ["curl"], "Fetch an explicitly permitted HTTP resource or probe a local service.", "Use only when the job network policy permits egress; use a protocol-specific client when one exists.", "curl --fail --silent --show-error http://127.0.0.1:8080/health", ["--fail", "--silent", "--show-error", "--location", "--output"]],
  ["ripgrep", "13.0.0-4+b2", ["rg"], "Find source symbols, strings, configuration keys, or references in a bounded workspace.", "Prefer rg for text search; use a parser or compiler database for syntax and semantic relationships.", "rg --line-number --glob '!node_modules' 'TODO' /workspace", ["--line-number", "--glob", "--type", "--hidden"]],
  ["jq", "1.6-2.1+deb12u2", ["jq"], "Inspect and transform JSON manifests, receipts, and machine-readable tool output.", "Use jq for JSON only; preserve the original file because a transformed view is not evidence of the source.", "jq -e '.status' result.json", ["-e", "-r", "--arg", "filter"]],
  ["file", "1:5.44-3", ["file"], "Identify an unknown artifact before selecting an analyzer.", "Use file as a fast type hint; confirm with format-specific parsers or ELF metadata before drawing conclusions.", "file --brief artifact.bin", ["--brief", "--mime-type", "--dereference"]],
  ["unzip", "6.0-28", ["unzip"], "List or extract ZIP based APK, HAP, bundles, and ordinary archives.", "Use unzip for archive structure and extraction; use apktool/JADX/bundletool for format-aware Android analysis.", "unzip -l sample.apk", ["-l", "-q", "-o", "-d"]],
  ["xz-utils", "5.4.1-1", ["xz", "unxz"], "Decompress source and tool archives supplied as xz files.", "Use it only for decompression; retain the original archive and verify its hash first.", "xz --decompress --keep archive.tar.xz", ["--decompress", "--keep", "--stdout"]],
  ["node", "22 (base image digest pinned)", ["node"], "Run JavaScript smoke checks, local parsers, or an installed Agent CLI.", "Use Node for JavaScript and package entrypoints; use Python or a format-specific tool for other data models.", "node --version", ["--version", "-e", "script path"]],
  ["npm", "bundled with Node 22 base image", ["npm"], "Inspect or run an already-installed package entrypoint in the image.", "Do not install packages during a job; the image snapshot is the authority.", "npm --version", ["--version", "exec", "prefix"]],
  ["npx", "bundled with Node 22 base image", ["npx"], "Invoke a package binary only when it is already present in the frozen image.", "Do not let npx download from the network; use a declared image package.", "npx --no-install --help", ["--no-install", "--package"]],
  ["claude-code", "2.1.258", ["claude"], "Run the declared Claude Code Agent runtime within the Scheduler-controlled job.", "Use the CLI selected in the job snapshot; the CLI is an Agent runtime, not an audit result generator.", "claude --version", ["--version", "working directory", "job runtime options"]],
  ["pi-coding-agent", "0.85.1", ["pi"], "Run the declared Pi Agent runtime for an image-compatible job.", "Use Pi when the frozen snapshot selects it; its web extension is available only in the audit variant.", "pi --version", ["--version", "working directory", "session options"]],
  ["dsh-sdk-jsonrpc-demo", "0.1.1-rc.2", ["dsh"], "Run the DSH Agent runtime and its governed JSON-RPC control surface.", "Use DSH only through the Scheduler-provided job token and control API; ordinary text or shell output is not a control event.", "dsh --help", ["--help", "workspace", "session"]],
  ["ca-certificates", "20230311+deb12u1", [], "Provide TLS trust for permitted HTTPS operations.", "This is a runtime dependency; it is not a substitute for the Scheduler network policy.", "not directly callable", [], true],
  ["dsh-runtime-modules", "0.1.1-rc.2 (plus dsh-reasoning-settings 0.3.0)", [], "Support the DSH CLI's protocol, skill, sandbox, subprocess, filesystem, session, token, code-runtime, and compaction modules.", "These packages are implementation dependencies; Agents use the dsh entrypoint and governed operations.", "not directly callable", [], true]
];

const baseSourcePointers = {
  git: "apt.git", python3: "apt.python3", curl: "apt.curl", ripgrep: "apt.ripgrep", jq: "apt.jq", file: "apt.file", unzip: "apt.unzip", "xz-utils": "apt.xz-utils",
  node: "baseImage", npm: "baseImage", npx: "baseImage", "claude-code": "npm.@anthropic-ai/claude-code", "pi-coding-agent": "npm.@earendil-works/pi-coding-agent", "dsh-sdk-jsonrpc-demo": "npm.@deepseek-ai/dsh-sdk-jsonrpc-demo"
};
const baseManifestCovers = {
  "claude-code": ["@anthropic-ai/claude-code"],
  "pi-coding-agent": ["@earendil-works/pi-coding-agent"],
  "dsh-sdk-jsonrpc-demo": ["@deepseek-ai/dsh-sdk-jsonrpc-demo"]
};
const makeBase = (imageKey, source = "agent-harness/runtime-images.json") => baseApt.map(([id, version, commands, scenario, selection, invocation, params, implementationOnly]) => entry(imageKey, {
  id,
  kind: implementationOnly ? "implementation_dependency" : "tool",
  implementation_only: Boolean(implementationOnly),
  version,
  version_source: `${source}#${id === "dsh-runtime-modules" ? "npm.supporting_modules" : baseSourcePointers[id] ?? "apt.ca-certificates"}`,
  commands,
  usage_scenario: scenario,
  selection_basis: selection,
  covers: baseManifestCovers[id],
  prerequisites: implementationOnly ? ["Use the corresponding Agent runtime; package internals are not a direct command surface."] : ["Use a frozen job workspace.", "Check the command version before relying on output."],
  minimal_invocation: invocation,
  common_parameters: params,
  output_interpretation: id === "git" ? "Commit, branch, and diff output establish source provenance; status alone does not prove source contents are safe." : undefined,
  composition_flow: id === "rg" ? "Search first, then pass selected files to a parser, compiler, or format-specific analyzer." : id === "file" ? "Use the type hint to select unzip, binutils, or a format-specific parser." : undefined,
  version_limits_side_effects_cleanup: implementationOnly ? "Not a direct Agent tool. Version is pinned for the corresponding runtime; do not mutate or replace package files in a job." : undefined
}));

const dshModules = [
  "@deepseek-ai/dsh-sdk-jsonrpc-server", "@deepseek-ai/dsh-sdk-protocol", "@deepseek-ai/dsh-agent-spine-demo", "@deepseek-ai/dsh-skill", "@deepseek-ai/dsh-skill-filesystem", "@deepseek-ai/dsh-tool-skill", "@deepseek-ai/dsh-llm-pi-ai", "dsh-reasoning-settings", "@deepseek-ai/dsh-sandbox-local", "@deepseek-ai/dsh-sandbox-policy", "@deepseek-ai/dsh-subprocess-local", "@deepseek-ai/dsh-bash-local", "@deepseek-ai/dsh-fs-local", "@deepseek-ai/dsh-tool-bash", "@deepseek-ai/dsh-tool-str-replace-editor", "@deepseek-ai/dsh-session-persistence-jsonl", "@deepseek-ai/dsh-session-checkpoint-policy", "@deepseek-ai/dsh-token-meter", "@deepseek-ai/dsh-code-runtime", "@deepseek-ai/dsh-code-runtime-worker-thread", "@deepseek-ai/dsh-compaction-basic"
];

const addDshModules = (imageKey, source = "agent-harness/runtime-images.json") => dshModules.map((id) => entry(imageKey, {
  id,
  kind: "implementation_dependency",
  implementation_only: true,
  agent_visible: false,
  version: id === "dsh-reasoning-settings" ? "0.3.0" : "0.1.1-rc.2",
  version_source: `${source}#npm.${id}`,
  commands: [],
  usage_scenario: "Internal dependency loaded by the dsh Agent runtime.",
  selection_basis: "Agents select dsh; they do not invoke this package as a second execution channel.",
  prerequisites: ["The dsh CLI and Scheduler-controlled runtime are present."],
  minimal_invocation: "not directly callable",
  common_parameters: [],
  output_interpretation: "No direct output contract; surfaced behavior must be attributed to the governed dsh operation and receipt.",
  composition_flow: "dsh -> Scheduler control API -> durable receipt/evidence.",
  evidence_retention: ["dsh command", "job and attempt identifiers", "Scheduler receipt"],
  version_limits_side_effects_cleanup: "Do not import or replace this package from a job. The package is shipped only to support the pinned dsh runtime.",
  verification_status: "source_reviewed_not_shipped_as_command",
  verification_note: "Package is declared in the runtime manifest and has no standalone Agent command."
}));

const auditBase = (imageKey) => [
  entry(imageKey, {
    id: "binutils",
    version: "2.40-2",
    version_source: "agent-harness/runtime-images.json#apt.binutils",
    commands: ["objdump", "readelf", "nm", "strings", "addr2line", "ar", "as", "ld"],
    usage_scenario: "Inspect ELF headers, sections, symbols, relocations, and addresses for native artifacts.",
    selection_basis: "Use binutils for deterministic metadata and symbol observations; use radare2/LIEF or a compiler-aware analyzer for deeper relationships.",
    prerequisites: ["A native ELF or object file", "A writable output directory when redirecting output"],
    minimal_invocation: "readelf -hW target.so",
    common_parameters: ["-h", "-S", "-s", "-d", "-W", "--demangle"],
    output_interpretation: "Headers and symbol tables describe the supplied file. They do not prove reachability, exploitability, or runtime behavior.",
    composition_flow: "file -> readelf/objdump/nm -> compiler or native analyzer -> verified Fact.",
    version_limits_side_effects_cleanup: "Read-only by default; output can be large for stripped or statically linked objects. Keep the exact file hash and command."
  }),
  entry(imageKey, {
    id: "pi-web-access",
    kind: "capability",
    version: "0.29.0",
    version_source: "agent-harness/runtime-images.json#piExtensions.pi-web-access",
    commands: ["pi"],
    usage_scenario: "Use Pi's declared web search, content extraction, or URL fetch capability when the audit job permits egress.",
    selection_basis: "Use only for current external material required by the task; use local artifacts for reproducible audit evidence.",
    prerequisites: ["Audit image", "Pi runtime", "Scheduler network permission and egress", "A source URL or search question"],
    minimal_invocation: "pi --help",
    common_parameters: ["query", "URL", "result limit"],
    output_interpretation: "Returned pages and search results are external observations; retain URL, retrieval time, and response hash. They do not become repository facts automatically.",
    failure_handling: { missing_condition: "If egress is disallowed, report missing network condition and continue with local evidence when possible." },
    composition_flow: "web result -> saved source snapshot/URL metadata -> jq/rg -> evidence with provenance.",
    evidence_retention: ["query or URL", "retrieval timestamp", "network policy", "raw response hash", "extracted excerpt and source reference"],
    version_limits_side_effects_cleanup: "Requires egress and can change with remote content. Avoid sending secrets in queries; clean response caches after retaining evidence."
  })
];

const def = (imageKey, id, version, source, commands, usage, selection, invocation, params, extra = {}) => entry(imageKey, {
  id, version, version_source: source, commands,
  usage_scenario: usage, selection_basis: selection, minimal_invocation: invocation, common_parameters: params, ...extra
});

const wrapper = (imageKey, id, commands, source, usage, selection, invocation, params, extra = {}) => def(imageKey, id, "image wrapper", source, commands, usage, selection, invocation, params, {
  kind: "wrapper",
  prerequisites: ["The corresponding runtime image", "A job workspace and explicit input/output paths"],
  verification_status: "source_reviewed_unexecuted",
  verification_note: "Wrapper source was reviewed; no Docker image was built or executed by this catalog generation.",
  ...extra
});

const capability = (imageKey, id, version, source, commands, usage, selection, invocation, params, extra = {}) => def(imageKey, id, version, source, commands, usage, selection, invocation, params, { kind: "capability", ...extra });

const makeImage = (imageKey, sourceFiles, inheritedFrom, defs, sections) => {
  const entries = defs;
  return {
    image_key: imageKey,
    manual_path: `/opt/deepsonar/manuals/images/${imageKey}/index.md`,
    self_contained: true,
    inherited_from: inheritedFrom,
    source_files: sourceFiles,
    sections,
    entries,
    entry_count: entries.length,
    agent_visible_entry_count: entries.filter((x) => x.agent_visible).length,
    implementation_only_entry_count: entries.filter((x) => x.implementation_only).length
  };
};

const commonBase = (imageKey) => [...makeBase(imageKey), ...addDshModules(imageKey)];
const baseSource = "agent-harness/runtime-images.json";

const images = [];
images.push(makeImage("deepsonar-base", ["agent-harness/runtime-images.json", "deploy/Dockerfile.agent", "agent-harness/write-tool-manifest.mjs"], [], commonBase("deepsonar-base"), ["base utilities", "Agent CLIs", "DSH implementation dependencies"]));
images.push(makeImage("deepsonar-audit", ["agent-harness/runtime-images.json", "deploy/Dockerfile.agent", "deploy/pi-web-access"], [], [...commonBase("deepsonar-audit"), ...auditBase("deepsonar-audit")], ["base utilities", "Agent CLIs", "binary inspection", "Pi web access"]));

const kaliCommon = [
  ["ca-certificates", "dpkg", [], "Provide TLS trust for permitted HTTPS operations.", "Runtime dependency; network permission remains Scheduler-controlled.", "not directly callable", [], true],
  ["curl", "dpkg", ["curl"], "Fetch an explicitly permitted HTTP resource or probe a local service.", "Use only for permitted egress or local endpoints.", "curl --fail --silent --show-error http://127.0.0.1:8080/health", ["--fail", "--silent", "--show-error", "--output"]],
  ["git", "dpkg", ["git"], "Inspect source history and preserve commit provenance.", "Use git for repository state; use rg or language analyzers for content and semantics.", "git status --short", ["--status", "--diff"]],
  ["ripgrep", "dpkg", ["rg"], "Search bounded source and artifact text.", "Use a parser or compile database for semantic relationships.", "rg --line-number pattern /workspace", ["--line-number", "--glob", "--type"]],
  ["jq", "dpkg", ["jq"], "Inspect JSON manifests and tool output.", "Use jq only for JSON and preserve the source file.", "jq -e '.status' result.json", ["-e", "-r", "filter"]],
  ["file", "dpkg", ["file"], "Identify artifacts before choosing a format-specific analyzer.", "Treat it as a type hint and confirm with a parser.", "file --brief artifact", ["--brief", "--mime-type"]],
  ["unzip", "dpkg", ["unzip"], "List or extract archives and package contents.", "Use format-aware tools when their evidence model is needed.", "unzip -l sample.apk", ["-l", "-o", "-d"]],
  ["xz-utils", "dpkg", ["xz", "unxz"], "Decompress xz archives while preserving the source.", "Use only for archive handling.", "xz --decompress --keep archive.tar.xz", ["--decompress", "--keep"]],
  ["python3", "dpkg", ["python3"], "Run deterministic glue scripts.", "Use the managed Python selectors for project-specific dependencies.", "python3 -c 'print(40 + 2)'", ["-c", "script path"]],
  ["python3-venv", "dpkg", [], "Provide isolated Python environments for project tooling.", "Use uv-managed environments where possible.", "python3 -m venv .venv", ["-m", "venv"], true],
  ["binutils", "dpkg", ["objdump", "readelf", "nm", "strings", "addr2line"], "Inspect native ELF metadata and symbols.", "Use binutils for metadata; use radare2 or a compiler analyzer for deeper analysis.", "readelf -hW target.so", ["-h", "-S", "-s", "-d", "-W"]],
  ["build-essential", "dpkg", ["cc", "gcc", "c++", "g++", "make"], "Compile a small native sample or a project that supplies complete build context.", "Use the project's declared build system and flags; do not infer security conclusions from a clean build.", "cc -Wall -Wextra -o sample sample.c", ["-I", "-D", "-L", "-l", "-o"]],
  ["pkg-config", "dpkg", ["pkg-config"], "Resolve compiler and linker flags for installed native dependencies.", "Use it only when the project build expects pkg-config metadata.", "pkg-config --cflags --libs zlib", ["--cflags", "--libs", "--modversion"]],
  ["golang-go", "dpkg", ["go"], "Build or test Go source with the repository's module context.", "Use Go only when go.mod and the target build context are available.", "go version", ["version", "test", "build", "-tags", "-o"]],
  ["rustc-cargo", "dpkg", ["rustc", "cargo"], "Build or test Rust source with Cargo metadata.", "Use Cargo for project builds and rustc for minimal compiler probes.", "cargo test --locked", ["--locked", "--offline", "--release", "--manifest-path"]]
];
const makeKaliCommon = () => kaliCommon.map(([id, version, commands, usage, selection, invocation, params, implementationOnly]) => def("deepsonar-kali-minimal", id, version, "agent-harness/kali-minimal-runtime.json#" + (id === "rustc-cargo" ? "apt.rustc/cargo" : `apt.${id}`), commands, usage, selection, invocation, params, { implementation_only: Boolean(implementationOnly), agent_visible: !implementationOnly }));
const kaliExtras = [
  def("deepsonar-kali-minimal", "node", "22.23.2", "agent-harness/kali-minimal-runtime.json#/downloads.node", ["node"], "Run JavaScript tooling and installed Agent package entrypoints.", "Use Node for JavaScript; do not download packages during a job.", "node --version", ["--version", "-e"]),
  def("deepsonar-kali-minimal", "npm", "22.23.2 bundled npm", "agent-harness/kali-minimal-runtime.json#/downloads.node", ["npm", "npx"], "Inspect or run already-installed JavaScript packages.", "Use only frozen package contents; npx must not fetch.", "npm --version", ["--version", "exec", "--no-install"]),
  def("deepsonar-kali-minimal", "claude-code", "2.1.258", "agent-harness/kali-minimal-runtime.json#/npm.@anthropic-ai/claude-code", ["claude"], "Run the declared Claude Code Agent runtime.", "Use the CLI selected in the frozen job snapshot.", "claude --version", ["--version"], { covers: ["@anthropic-ai/claude-code"] }),
  def("deepsonar-kali-minimal", "pi-coding-agent", "0.85.1", "agent-harness/kali-minimal-runtime.json#/npm.@earendil-works/pi-coding-agent", ["pi"], "Run the declared Pi Agent runtime.", "Use the CLI selected in the frozen job snapshot.", "pi --version", ["--version"], { covers: ["@earendil-works/pi-coding-agent"] }),
  def("deepsonar-kali-minimal", "dsh-sdk-jsonrpc-demo", "0.1.1-rc.2", "agent-harness/kali-minimal-runtime.json#/npm.@deepseek-ai/dsh-sdk-jsonrpc-demo", ["dsh"], "Run the governed DSH Agent runtime.", "Use only Scheduler-issued control credentials and operations.", "dsh --help", ["--help"], { covers: ["@deepseek-ai/dsh-sdk-jsonrpc-demo"] }),
  def("deepsonar-kali-minimal", "uv", "0.11.32", "agent-harness/kali-minimal-runtime.json#/downloads.uv", ["uv"], "Select a declared Python version or resolve packages from an already-authorized source.", "Use uv for managed Python versions and offline or lockfile-bound environments; do not bootstrap arbitrary packages.", "uv --version", ["python", "venv", "pip", "--offline"]),
  ...["3.10.20", "3.11.15", "3.12.13", "3.13.14", "3.14.6"].map((v) => def("deepsonar-kali-minimal", `python${v.split(".").slice(0, 2).join(".")}`, v, "agent-harness/kali-minimal-runtime.json#/managed.python.versions", [`python${v.split(".").slice(0, 2).join(".")}`], "Run a project or sample with the matching declared Python minor version.", "Select the version required by the project; default python3 is the image default 3.14.6.", `python${v.split(".").slice(0, 2).join(".")} --version`, ["--version", "-m", "-c"], v === "3.14.6" ? { covers: ["python"] } : {})),
  def("deepsonar-kali-minimal", "jdk-8", "8u492-b09", "agent-harness/kali-minimal-runtime.json#/managed.jdk.versions[0]", ["java8", "javac8"], "Build or run projects constrained to Java 8.", "Use the project-required major; do not use Java 8 to explain Java 17 behavior.", "java8 -version", ["-version", "-cp", "-jar"]),
  def("deepsonar-kali-minimal", "jdk-11", "11.0.31+11", "agent-harness/kali-minimal-runtime.json#/managed.jdk.versions[1]", ["java11", "javac11"], "Build or run projects constrained to Java 11.", "Use the project-required major and preserve JAVA_HOME in evidence.", "java11 -version", ["-version", "-cp", "-jar"]),
  def("deepsonar-kali-minimal", "jdk-17", "17.0.19+10", "agent-harness/kali-minimal-runtime.json#/managed.jdk.versions[2]", ["java", "javac", "jar"], "Build or run projects requiring the default Java 17 runtime.", "Use Java 17 only when project metadata permits it; record selected JAVA_HOME.", "java -version", ["-version", "-cp", "-jar", "--release"], { covers: ["jdk"] }),
  def("deepsonar-kali-minimal", "maven", "3.9.16", "agent-harness/kali-minimal-runtime.json#/downloads.maven", ["mvn"], "Build or test Maven projects with a present pom.xml and locked dependency policy.", "Use Maven when the repository declares Maven; do not download dependencies without network permission.", "mvn -version", ["-o", "-DskipTests", "-pl", "-am", "-f"]),
  def("deepsonar-kali-minimal", "pi-web-access", "0.29.0", "agent-harness/kali-minimal-runtime.json#/piExtensions.pi-web-access", ["pi"], "Use Pi's declared web search, content extraction, or URL fetch capability when the job permits egress.", "Use only for task-required current external material; preserve URL and retrieval provenance.", "pi --help", ["query", "URL", "result limit"], { kind: "capability", requires_egress: true, covers: ["pi-web-access"], failure_handling: { missing_condition: "If egress is disallowed, record missing network condition and continue with local evidence when possible." } }),
  ...addDshModules("deepsonar-kali-minimal", "agent-harness/kali-minimal-runtime.json")
];
images.push(makeImage("deepsonar-kali-minimal", ["agent-harness/kali-minimal-runtime.json", "deploy/Dockerfile.agent-kali-minimal"], [], [...makeKaliCommon(), ...kaliExtras], ["common utilities", "multi-version Python", "Go/Rust", "Java 8/11/17", "Maven", "Agent CLIs"]));

const chromeTestDefs = (imageKey) => [
  def(imageKey, "chromium", "151.0.7922.71-1~deb12u1", "agent-harness/chrome-test-runtime.json#/apt.chromium", ["chromium"], "Launch a browser to observe page behavior, DOM, navigation, and browser artifacts.", "Use Chromium/CDP for real browser behavior; use Playwright for structured interaction after CDP connects.", "chromium --version", ["--headless=new", "--remote-debugging-port", "--user-data-dir", "--no-sandbox"]),
  def(imageKey, "chromium-common", "151.0.7922.71-1~deb12u1", "agent-harness/chrome-test-runtime.json#/apt.chromium-common", [], "Provide Chromium runtime files.", "Implementation package for the chromium command.", "not directly callable", [], { kind: "implementation_dependency", agent_visible: false, implementation_only: true }),
  def(imageKey, "playwright-core", "1.62.1", "agent-harness/chrome-test-runtime.json#/npm.playwright-core", ["node"], "Connect to the already-running browser over CDP and inspect page state.", "Use Playwright after a governed browser is running; use raw CDP only for protocol-level observations.", "node -e \"require('playwright-core')\"", ["chromium.connectOverCDP", "browserContext", "page.goto"]),
  wrapper(imageKey, "chrome-headless.sh", ["/opt/deepsonar/bin/chrome-headless.sh"], "deploy/chrome-headless.sh", "Start the governed headless Chromium process with a bounded port, profile directory, and URL.", "Use this wrapper instead of constructing an unbounded Chromium command.", "/opt/deepsonar/bin/chrome-headless.sh --port 9222 --user-data-dir /workspace/chrome-profile --url http://127.0.0.1:8080/", ["--port", "--user-data-dir", "--url"], { covers: ["chromium-headless"], failure_handling: { missing_condition: "Reject non-workspace profile paths or unavailable Chromium; report the exact validation error." } }),
  wrapper(imageKey, "chrome-test-env.sh", ["/opt/deepsonar/bin/chrome-test-env.sh --check"], "deploy/chrome-test-env.sh", "Verify the browser, Node, Playwright/CDP smoke prerequisites, and manifest before a browser test.", "Use the check as a preflight; it does not establish application behavior.", "/opt/deepsonar/bin/chrome-test-env.sh --check", ["--check"]),
  wrapper(imageKey, "chrome-test-smoke.mjs", ["node /opt/deepsonar/chrome-test-smoke.mjs"], "agent-harness/chrome-test-smoke.mjs", "Run the fixed local CDP smoke sample to verify launch, connection, navigation, and cleanup.", "Use only as an environment check; use a task-specific test for product evidence.", "node /opt/deepsonar/chrome-test-smoke.mjs", ["PORT", "workspace temp directory"], { kind: "capability", failure_handling: { normal_empty: "A page with no optional content is still a successful smoke result if the expected title and #ok marker are present." } }),
  capability(imageKey, "chromium-cdp", "151.0.7922.71 / Playwright 1.62.1", "deploy/Dockerfile.agent-chrome-test#inline manifest", ["chromium", "/opt/deepsonar/bin/chrome-headless.sh", "node"], "Observe a real browser through its local CDP endpoint.", "Choose CDP when browser process state and page behavior matter; use static HTML parsing for saved markup only.", "wrapper -> GET http://127.0.0.1:9222/json/version -> playwright chromium.connectOverCDP", ["port", "user-data-dir", "URL", "page selector"], { covers: ["remote-debugging-cdp"], prerequisites: ["A permitted local browser launch", "A unique port and workspace profile", "Playwright core"], composition_flow: "headless wrapper -> /json/version -> Playwright page observation -> saved DOM/network/screenshot artifacts." })
];
images.push(makeImage("deepsonar-chrome-test", ["agent-harness/chrome-test-runtime.json", "deploy/Dockerfile.agent-chrome-test", "deploy/chrome-headless.sh", "deploy/chrome-test-env.sh", "agent-harness/chrome-test-smoke.mjs"], ["deepsonar-base"], [...commonBase("deepsonar-chrome-test"), ...chromeTestDefs("deepsonar-chrome-test")], ["inherited base tools", "Chromium", "CDP", "Playwright", "browser wrappers"]));

const chromeAuditDefs = (imageKey) => [
  def(imageKey, "clang", "Debian snapshot (exact version not pinned)", "agent-harness/chrome-audit-runtime.json#/apt.clang", ["clang", "clang++"], "Compile or inspect C/C++ with the repository's compilation flags.", "Use Clang when compile context is available; do not use it as a source-only vulnerability scanner.", "clang --version", ["-I", "-D", "-std", "-fsyntax-only", "-o"]),
  def(imageKey, "clang-tidy", "Debian snapshot (exact version not pinned)", "agent-harness/chrome-audit-runtime.json#/apt.clang-tidy", ["clang-tidy"], "Run compiler-aware checks against C/C++ files with compile_commands.json.", "Use clang-tidy when compile commands are available; use rg for initial discovery and a parser for custom semantics.", "clang-tidy -p build src/file.cc", ["-p", "-checks", "--header-filter", "--export-fixes"]),
  def(imageKey, "clangd", "Debian snapshot (exact version not pinned)", "agent-harness/chrome-audit-runtime.json#/apt.clangd", ["clangd"], "Provide language-server semantic indexing when an editor or index client is available.", "Use clangd for symbol and compile-context navigation; use clang-tidy for batch findings.", "clangd --version", ["--compile-commands-dir", "--background-index"]),
  def(imageKey, "llvm", "Debian snapshot (exact version not pinned)", "agent-harness/chrome-audit-runtime.json#/apt.llvm", ["llvm-nm"], "Inspect LLVM symbols and object metadata.", "Use LLVM utilities when the artifact or build uses LLVM naming/metadata; binutils is the portable ELF fallback.", "llvm-nm --version", ["--defined-only", "--demangle", "--format"]),
  def(imageKey, "binutils", "Debian snapshot (exact version not pinned)", "agent-harness/chrome-audit-runtime.json#/apt.binutils", ["objdump", "readelf", "nm"], "Inspect native binary headers, sections, symbols, and disassembly.", "Use it for deterministic file observations; use Clang tools for source/build context.", "readelf -hW target", ["-h", "-S", "-s", "-d", "-W"]),
  capability(imageKey, "git-partial-clone", "git 1:2.39.5-0+deb12u3", "deploy/Dockerfile.agent-chrome-audit#inline manifest", ["git"], "Materialize only the source history needed for a bounded audit.", "Use a partial clone when repository size is the constraint and server support is available; use a full clone when complete history is evidence.", "git clone --filter=blob:none --no-checkout URL source", ["--filter=blob:none", "--no-checkout", "--depth"], { prerequisites: ["Permitted repository access", "A repository URL or local mirror", "A writable workspace"] }),
  wrapper(imageKey, "chrome-audit-env.sh", ["/opt/deepsonar/bin/chrome-audit-env.sh --check"], "deploy/chrome-audit-env.sh", "Verify the C/C++ audit toolchain, manifest, and the deliberate absence of decision scanners.", "Run before an audit; it does not replace a source audit.", "/opt/deepsonar/bin/chrome-audit-env.sh --check", ["--check"], { failure_handling: { missing_condition: "If compile tools or compile context are absent, record an inconclusive audit precondition; do not install tools during the job." } })
];
images.push(makeImage("deepsonar-chrome-audit", ["agent-harness/chrome-audit-runtime.json", "deploy/Dockerfile.agent-chrome-audit", "deploy/chrome-audit-env.sh"], ["deepsonar-base"], [...commonBase("deepsonar-chrome-audit"), ...chromeAuditDefs("deepsonar-chrome-audit")], ["inherited base tools", "Clang/LLVM", "ELF inspection", "partial source materialization"]));

const chromeFuzzDefs = (imageKey) => [
  def(imageKey, "clang-16", "16.0.6-15~deb12u1", "agent-harness/chrome-fuzz-runtime.json#/apt.clang", ["clang-16", "clang++-16"], "Compile a V8 or native fuzz harness with the pinned compiler runtime.", "Use the pinned compiler for sanitizer and V8 compatibility; do not substitute the host compiler.", "clang-16 --version", ["-fsanitize", "-fno-omit-frame-pointer", "-I", "-o"]),
  def(imageKey, "lld-16", "16.0.6-15~deb12u1", "agent-harness/chrome-fuzz-runtime.json#/apt.lld", ["lld-16"], "Link fuzz targets with the pinned LLVM linker.", "Use it when the target build requires lld; retain linker flags in evidence.", "lld-16 --version", ["-o", "--sysroot"]),
  def(imageKey, "llvm-16", "16.0.6-15~deb12u1", "agent-harness/chrome-fuzz-runtime.json#/apt.llvm", ["llvm-symbolizer"], "Symbolize sanitizer and fuzz crash addresses.", "Use llvm-symbolizer matching the compiler runtime; mismatched symbols make stack evidence unreliable.", "llvm-symbolizer --version", ["--obj", "--inlining", "--demangle"]),
  def(imageKey, "compiler-rt", "16.0.6-15~deb12u1", "agent-harness/chrome-fuzz-runtime.json#/apt.compiler-rt", ["clang-16"], "Supply sanitizer runtime libraries for instrumented fuzz targets.", "Use as a link dependency selected by the compiler; it has no standalone finding output.", "clang-16 -fsanitize=address -o sample sample.c", ["-fsanitize=address", "-fsanitize=fuzzer"], { kind: "runtime_dependency", output_interpretation: "The runtime changes observations and crash diagnostics; it does not prove the uninstrumented binary has the same behavior." }),
  def(imageKey, "libFuzzer-16", "16.0.6-15~deb12u1", "agent-harness/chrome-fuzz-runtime.json#/apt.libfuzzer", [], "Link and run libFuzzer targets with a seed corpus.", "Use libFuzzer for in-process harnesses; use AFL++ when fork or coverage workflow is required.", "target -runs=1 corpus/seed", ["-runs", "-max_total_time", "-artifact_prefix", "-jobs", "-workers"], { kind: "runtime_dependency" }),
  def(imageKey, "AFL++", "Debian package (exact version not pinned)", "agent-harness/chrome-fuzz-runtime.json#/apt.afl++", ["afl-fuzz", "afl-clang-fast"], "Run forkserver or AFL++ instrumented fuzzing when the harness supports it.", "Choose AFL++ for its corpus and forkserver workflow; choose libFuzzer for in-process targets.", "afl-fuzz -i corpus/in -o corpus/out -- ./target @@", ["-i", "-o", "-m", "-t", "-M", "-S"]),
  def(imageKey, "binutils", "Debian snapshot (exact version not pinned)", "agent-harness/chrome-fuzz-runtime.json#/apt.binutils", ["objdump", "readelf"], "Inspect the produced fuzz target and crash artifact.", "Use it to confirm architecture and symbols before interpreting a crash.", "readelf -hW d8", ["-h", "-S", "-s", "-W"]),
  def(imageKey, "d8", "V8 15.1.206.10; commit 792d9716...", "agent-harness/chrome-fuzz-runtime.json#/v8", ["d8"], "Run JavaScript seeds against the actual V8 shell built for this image.", "Use d8 for V8 engine behavior; use a browser wrapper for browser APIs and DOM behavior.", "d8 --version", ["--allow-natives-syntax", "--expose-gc", "seed.js"]),
  def(imageKey, "v8_json_libfuzzer", "V8 target at commit 792d9716...", "agent-harness/chrome-fuzz-runtime.json#/v8.target", ["v8_json_libfuzzer"], "Run the V8 JSON libFuzzer target with a bounded JSON corpus.", "Use this target only for its declared JSON harness; malformed non-JSON input is a harness error.", "v8_json_libfuzzer -runs=1 corpus/seed.json", ["-runs", "-max_total_time", "-artifact_prefix", "-timeout"]),
  capability(imageKey, "v8-fuzz-target", "V8 15.1.206.10", "deploy/Dockerfile.agent-chrome-fuzz#inline manifest", ["d8", "v8_json_libfuzzer"], "Generate, execute, and minimize V8 JavaScript or JSON fuzz inputs.", "Use d8 for direct JS probes and v8_json_libfuzzer for the JSON harness; keep seed format aligned with target input.", "seed JSON -> v8_json_libfuzzer -runs=1 corpus -> crash artifact", ["seed corpus", "-runs", "-max_total_time", "-artifact_prefix"], { prerequisites: ["Actual V8 target", "Valid seed corpus", "Bounded time and disk budget"] }),
  wrapper(imageKey, "chrome-fuzz-env.sh", ["/opt/deepsonar/bin/chrome-fuzz-env.sh --check"], "deploy/chrome-fuzz-env.sh", "Verify the actual V8 target, compiler runtime, symbolizer, and fuzzer commands.", "Use before fuzzing; source checks are not a crash result.", "/opt/deepsonar/bin/chrome-fuzz-env.sh --check", ["--check", "--static"]),
  wrapper(imageKey, "chrome-fuzz-smoke.sh", ["/opt/deepsonar/bin/chrome-fuzz-smoke.sh"], "deploy/chrome-fuzz-smoke.sh", "Run the fixed d8 arithmetic and one JSON libFuzzer seed smoke test.", "Use only to validate image wiring; use a task-specific corpus for research.", "/opt/deepsonar/bin/chrome-fuzz-smoke.sh", [], { failure_handling: { normal_empty: "A fuzzer may produce no crash and still pass the smoke assertion; that is a no-crash observation for the fixed seed only." } }),
  entry(imageKey, { id: "v8-build-source", kind: "implementation_dependency", implementation_only: true, agent_visible: false, version: "commit 792d9716...", version_source: "agent-harness/chrome-fuzz-runtime.json#/v8.source", commands: [], covers: ["v8-source"], usage_scenario: "Build-time V8 source used to produce d8 and the JSON libFuzzer target.", selection_basis: "Not a final image command; the runtime must use the produced pinned binaries.", prerequisites: ["V8 build stage and depot_tools"], minimal_invocation: "not shipped as a final Agent command", common_parameters: [], output_interpretation: "Build logs and commit identify the binary provenance.", composition_flow: "V8 source -> GN/Ninja build -> d8/v8_json_libfuzzer -> fuzz evidence.", evidence_retention: ["V8 commit", "depot_tools commit", "GN args", "build log", "binary hash"], version_limits_side_effects_cleanup: "Build-only source and preflight artifacts are not available to the Agent in the final scratch image.", verification_status: "source_reviewed_not_shipped_as_command", verification_note: "Dockerfile copies binaries, libraries, wrappers, and smoke assets into the final image; build source remains in a builder stage." }),
  entry(imageKey, { id: "chrome-fuzz-toolchain-preflight.sh", kind: "implementation_dependency", implementation_only: true, agent_visible: false, version: "image build script", version_source: "deploy/chrome-fuzz-toolchain-preflight.sh", commands: [], usage_scenario: "Inspect GN/Ninja build configuration during image construction.", selection_basis: "Maintainer build preflight only; Agents use chrome-fuzz-env.sh and the shipped targets.", prerequisites: ["V8 builder stage"], minimal_invocation: "not shipped as a final Agent command", common_parameters: [], output_interpretation: "Preflight output describes build configuration, not target behavior.", composition_flow: "preflight -> V8 build -> final target smoke.", evidence_retention: ["preflight output", "build logs", "source commit"], version_limits_side_effects_cleanup: "Not copied to the final image.", verification_status: "source_reviewed_not_shipped_as_command", verification_note: "Dockerfile uses it in the builder stage only." })
];
images.push(makeImage("deepsonar-chrome-fuzz", ["agent-harness/chrome-fuzz-runtime.json", "deploy/Dockerfile.agent-chrome-fuzz", "deploy/chrome-fuzz-env.sh", "deploy/chrome-fuzz-smoke.sh", "deploy/chrome-fuzz-toolchain-preflight.sh"], ["deepsonar-base"], [...commonBase("deepsonar-chrome-fuzz"), ...chromeFuzzDefs("deepsonar-chrome-fuzz")], ["inherited base tools", "V8/d8", "libFuzzer", "AFL++", "sanitizer and crash evidence"]));

const clickhouseCommon = (imageKey, includeFuzz = false) => {
  const flavor = imageKey.match(/clickhouse-(audit|test|fuzz)$/)?.[1] ?? "test";
  const runtimeSource = `agent-harness/clickhouse-${flavor}-runtime.json#/clickhouse`;
  const dockerSource = `deploy/Dockerfile.agent-clickhouse-${flavor}#inline manifest`;
  return [
  def(imageKey, "clickhouse", "26.3.28.5", runtimeSource, ["clickhouse"], "Use the official ClickHouse binary for local SQL or server-backed observations.", "Use clickhouse-local for bounded local queries and clickhouse-server only when server behavior or HTTP/TCP protocol matters.", "clickhouse --version", ["--config-file", "--path", "--query", "--multiquery"]),
  def(imageKey, "clickhouse-local", "26.3.28.5", runtimeSource, ["clickhouse-local"], "Run deterministic SQL over local files or inline values without starting a server.", "Prefer local for isolated SQL and result interpretation; use server for protocol, settings, or lifecycle behavior.", "clickhouse-local --query 'SELECT 40 + 2'", ["--query", "--format", "--input-format", "--path"]),
  def(imageKey, "clickhouse-client", "26.3.28.5", runtimeSource, ["clickhouse-client"], "Query an already-authorized ClickHouse server over its client protocol.", "Use client only when a server endpoint and credentials/policy are explicitly provided; use local for self-contained evidence.", "clickhouse-client --host 127.0.0.1 --query 'SELECT 40 + 2'", ["--host", "--port", "--user", "--password", "--query"]),
  def(imageKey, "clickhouse-server", "26.3.28.5", runtimeSource, ["clickhouse-server"], "Run the official ClickHouse server binary when server lifecycle, settings, HTTP, or TCP behavior is part of the task.", "Use the governed clickhouse-server.sh wrapper so paths and ports remain bounded; use clickhouse-local for isolated SQL.", "clickhouse-server --version", ["--config-file", "--path", "--http-port", "--tcp-port"]),
  capability(imageKey, "clickhouse-sql", "26.3.28.5", dockerSource, ["clickhouse-local", "clickhouse-client"], "Execute SQL and explain rows, types, errors, and query settings.", "Choose local/client/server by required protocol and state; retain the exact query and format.", "clickhouse-local --format JSONEachRow --query 'SELECT 40 + 2 AS answer'", ["--query", "--format", "--database", "--max_threads"], { covers: ["clickhouse-http"], output_interpretation: "Rows and server errors are observations for the supplied data and settings; an empty result is not proof that no matching data exists outside the query scope." }),
  wrapper(imageKey, "clickhouse-sandbox-config.sh", ["/opt/deepsonar/bin/clickhouse-sandbox-config.sh"], "deploy/clickhouse-sandbox-config.sh", "Create a bounded local ClickHouse configuration and users file for a job workspace.", "Use it before clickhouse-server.sh; do not hand-write an unbounded server configuration.", "/opt/deepsonar/bin/clickhouse-sandbox-config.sh --path /workspace/ch-data --http-port 18123 --tcp-port 19000", ["--path", "--http-port", "--tcp-port"], { kind: "wrapper", failure_handling: { missing_condition: "Reject paths outside the workspace or ports that are already occupied; choose a new bounded path/port." } }),
  wrapper(imageKey, "clickhouse-server.sh", ["/opt/deepsonar/bin/clickhouse-server.sh"], "deploy/clickhouse-server.sh", "Start an isolated ClickHouse server when lifecycle or HTTP/TCP behavior is part of the task.", "Use local for pure SQL; use this wrapper for a server test with explicit workspace and ports.", "/opt/deepsonar/bin/clickhouse-server.sh --path /workspace/ch-data --http-port 18123 --tcp-port 19000", ["--path", "--http-port", "--tcp-port"], { failure_handling: { transient_retryable: "If startup races with port readiness, retain the server log, poll /ping within the timeout, and stop the process before retrying." } }),
  wrapper(imageKey, "clickhouse-test-env.sh", ["/opt/deepsonar/bin/clickhouse-test-env.sh --check"], "deploy/clickhouse-test-env.sh", "Verify ClickHouse aliases, version, Node, jq, and the test manifest.", "Use as a preflight before server/client test work.", "/opt/deepsonar/bin/clickhouse-test-env.sh --check", ["--check"]),
  wrapper(imageKey, "clickhouse-test-smoke.mjs", ["node /opt/deepsonar/clickhouse-test-smoke.mjs"], "agent-harness/clickhouse-test-smoke.mjs", "Run the fixed server /ping and SELECT 40+2 smoke path.", "Use only for runtime wiring; it does not validate application SQL.", "node /opt/deepsonar/clickhouse-test-smoke.mjs", ["HTTP_PORT", "workspace temp directory"], { kind: "capability" })
  ];
};

const clickhouseAuditDefs = (imageKey) => [
  def(imageKey, "cmake", "Debian snapshot (exact version not pinned)", "agent-harness/clickhouse-audit-runtime.json#/apt.cmake", ["cmake"], "Configure a ClickHouse C++ build with the repository's options.", "Use CMake when the source declares it; preserve cache and compiler flags.", "cmake -S . -B build", ["-S", "-B", "-D", "--build"]),
  def(imageKey, "ninja", "Debian snapshot (exact version not pinned)", "agent-harness/clickhouse-audit-runtime.json#/apt.ninja-build", ["ninja"], "Build a generated C++ target using the declared build graph.", "Use Ninja when the project generator emits build.ninja; use the repository's documented target.", "ninja -C build target", ["-C", "-j"]),
  def(imageKey, "clang-toolchain", "Debian snapshot (exact version not pinned)", "agent-harness/clickhouse-audit-runtime.json#/apt.clang", ["clang", "clang++", "clang-tidy", "clangd", "llvm-nm"], "Compile and inspect ClickHouse C++ with compiler-aware tools.", "Use clang-tidy with compile_commands.json; use binutils for standalone ELF metadata.", "clang-tidy -p build src/file.cpp", ["-p", "-checks", "-I", "-D", "--export-fixes"]),
  def(imageKey, "binutils", "Debian snapshot (exact version not pinned)", "agent-harness/clickhouse-audit-runtime.json#/apt.binutils", ["objdump", "readelf", "nm"], "Inspect native build products and symbol metadata.", "Use for deterministic binary observations; do not infer source reachability from symbols alone.", "readelf -hW build/bin", ["-h", "-S", "-s", "-d", "-W"]),
  capability(imageKey, "git-partial-clone", "git 1:2.39.5-0+deb12u3", "deploy/Dockerfile.agent-clickhouse-audit#inline manifest", ["git"], "Materialize a bounded ClickHouse source tree.", "Use partial clone for size constraints when complete history is not needed.", "git clone --filter=blob:none --no-checkout URL source", ["--filter=blob:none", "--no-checkout", "--depth"]),
  wrapper(imageKey, "clickhouse-audit-env.sh", ["/opt/deepsonar/bin/clickhouse-audit-env.sh --check"], "deploy/clickhouse-audit-env.sh", "Verify CMake/Ninja/Clang audit prerequisites and the absence of decision scanners.", "Run before static audit work.", "/opt/deepsonar/bin/clickhouse-audit-env.sh --check", ["--check"])
];
images.push(makeImage("deepsonar-clickhouse-audit", ["agent-harness/clickhouse-audit-runtime.json", "deploy/Dockerfile.agent-clickhouse-audit", "deploy/clickhouse-audit-env.sh"], ["deepsonar-base"], [...commonBase("deepsonar-clickhouse-audit"), ...clickhouseAuditDefs("deepsonar-clickhouse-audit")], ["inherited base tools", "CMake/Ninja", "Clang/LLVM", "ClickHouse C++ source audit"]));

const clickhouseFuzzDefs = (imageKey) => [
  def(imageKey, "clang-16", "16.0.6-15~deb12u1", "agent-harness/clickhouse-fuzz-runtime.json#/apt.clang", ["clang-16", "clang++-16"], "Compile a ClickHouse or native fuzz target with sanitizer instrumentation.", "Use the pinned compiler and target build flags; retain all sanitizer options.", "clang++-16 -fsanitize=fuzzer,address -o target target.cc", ["-fsanitize", "-fno-omit-frame-pointer", "-o"]),
  def(imageKey, "lld-16", "16.0.6-15~deb12u1", "agent-harness/clickhouse-fuzz-runtime.json#/apt.lld", ["lld-16"], "Link the fuzz target with the pinned LLVM linker.", "Use when the target build requires lld.", "lld-16 --version", ["-o"]),
  def(imageKey, "llvm-16", "16.0.6-15~deb12u1", "agent-harness/clickhouse-fuzz-runtime.json#/apt.llvm", ["llvm-symbolizer"], "Symbolize sanitizer crash addresses.", "Use the symbolizer matching the compiler runtime.", "llvm-symbolizer --version", ["--obj", "--inlining"]),
  def(imageKey, "compiler-rt", "16.0.6-15~deb12u1", "agent-harness/clickhouse-fuzz-runtime.json#/apt.compiler-rt", ["clang-16"], "Supply sanitizer runtime libraries.", "Link through the declared compiler; it has no standalone finding output.", "clang++-16 -fsanitize=address -o sample sample.cc", ["-fsanitize=address", "-fsanitize=undefined"], { kind: "runtime_dependency" }),
  def(imageKey, "libFuzzer-16", "16.0.6-15~deb12u1", "agent-harness/clickhouse-fuzz-runtime.json#/apt.libfuzzer", [], "Run an in-process ClickHouse fuzz target with a bounded corpus.", "Use libFuzzer for in-process targets; use AFL++ for forkserver workflows.", "target -runs=1 corpus/seed", ["-runs", "-max_total_time", "-artifact_prefix"], { kind: "runtime_dependency" }),
  def(imageKey, "AFL++", "Debian package (exact version not pinned)", "agent-harness/clickhouse-fuzz-runtime.json#/apt.afl++", ["afl-fuzz", "afl-clang-fast"], "Run AFL++ against a compatible target and corpus.", "Choose AFL++ when forkserver/corpus behavior is required.", "afl-fuzz -i corpus/in -o corpus/out -- ./target @@", ["-i", "-o", "-t", "-m"]),
  def(imageKey, "cmake-ninja", "Debian snapshot (exact version not pinned)", "agent-harness/clickhouse-fuzz-runtime.json#/apt.cmake", ["cmake", "ninja"], "Configure and build a reproducible fuzz target.", "Use the repository's build graph and retain generated compile commands.", "cmake -S . -B build -G Ninja", ["-S", "-B", "-G", "-D", "-C"]),
  def(imageKey, "clickhouse-local", "26.3.28.5", "agent-harness/clickhouse-fuzz-runtime.json#/clickhouse", ["clickhouse-local"], "Use the official local SQL binary as a fixed seed or oracle for query-related fuzz cases.", "Use it for SQL input/output checks; it is not a general-purpose C++ fuzz harness.", "clickhouse-local --query 'SELECT 40 + 2'", ["--query", "--format", "--path"]),
  wrapper(imageKey, "clickhouse-sandbox-config.sh", ["/opt/deepsonar/bin/clickhouse-sandbox-config.sh"], "deploy/clickhouse-sandbox-config.sh", "Create bounded data/config paths for local ClickHouse fuzz checks.", "Use before any server-backed check; local SQL can avoid a server.", "/opt/deepsonar/bin/clickhouse-sandbox-config.sh --path /workspace/ch-data --http-port 18123 --tcp-port 19000", ["--path", "--http-port", "--tcp-port"]),
  wrapper(imageKey, "clickhouse-fuzz-env.sh", ["/opt/deepsonar/bin/clickhouse-fuzz-env.sh --check"], "deploy/clickhouse-fuzz-env.sh", "Verify actual ClickHouse, compiler runtime, fuzzer, symbolizer, and manifest metadata.", "Run before fuzzing; it is not a crash result.", "/opt/deepsonar/bin/clickhouse-fuzz-env.sh --check", ["--check"]),
  wrapper(imageKey, "clickhouse-fuzz-smoke.sh", ["/opt/deepsonar/bin/clickhouse-fuzz-smoke.sh"], "deploy/clickhouse-fuzz-smoke.sh", "Run the fixed local SQL and seed smoke checks.", "Use only for image wiring and no-crash smoke evidence.", "/opt/deepsonar/bin/clickhouse-fuzz-smoke.sh", [], { kind: "capability" }),
  entry(imageKey, { id: "clickhouse-install-static.sh", kind: "implementation_dependency", implementation_only: true, agent_visible: false, version: "image build script", version_source: "deploy/clickhouse-install-static.sh", commands: [], usage_scenario: "Download and install the official ClickHouse static package during image construction.", selection_basis: "Build-only helper; Agents use clickhouse-local/client/server after installation.", prerequisites: ["Pinned URL and checksum", "Image build network"], minimal_invocation: "not shipped as a final Agent command", common_parameters: [], output_interpretation: "Installer logs establish package provenance only.", composition_flow: "official package -> checksum -> /opt/deepsonar/bin aliases -> runtime checks.", evidence_retention: ["URL", "checksum", "package version", "build log"], version_limits_side_effects_cleanup: "The helper is removed from the final image; do not download a replacement from a job.", verification_status: "source_reviewed_not_shipped_as_command", verification_note: "Used in Dockerfile build stage and not copied into the final scratch image." })
];
images.push(makeImage("deepsonar-clickhouse-test", ["agent-harness/clickhouse-test-runtime.json", "deploy/Dockerfile.agent-clickhouse-test", "deploy/clickhouse-install-static.sh", "deploy/clickhouse-sandbox-config.sh", "deploy/clickhouse-server.sh", "deploy/clickhouse-test-env.sh", "agent-harness/clickhouse-test-smoke.mjs"], ["deepsonar-base"], [...commonBase("deepsonar-clickhouse-test"), ...clickhouseCommon("deepsonar-clickhouse-test")], ["inherited base tools", "ClickHouse local/client/server", "SQL", "HTTP/TCP server wrappers"]));
images.push(makeImage("deepsonar-clickhouse-fuzz", ["agent-harness/clickhouse-fuzz-runtime.json", "deploy/Dockerfile.agent-clickhouse-fuzz", "deploy/clickhouse-install-static.sh", "deploy/clickhouse-sandbox-config.sh", "deploy/clickhouse-fuzz-env.sh", "deploy/clickhouse-fuzz-smoke.sh"], ["deepsonar-base"], [...commonBase("deepsonar-clickhouse-fuzz"), ...clickhouseFuzzDefs("deepsonar-clickhouse-fuzz")], ["inherited base tools", "ClickHouse local", "Clang/libFuzzer/AFL++", "SQL seed and crash evidence"]));

const ohCommon = (imageKey, test = false) => [
  def(imageKey, "git-lfs", "snapshot (exact apt version not pinned)", `agent-harness/${test ? "openharmony-test" : imageKey.includes("fuzz") ? "openharmony-fuzz" : "openharmony-audit"}-runtime.json#/apt.git-lfs`, ["git-lfs"], "Fetch large OpenHarmony source objects declared by the repository.", "Use it with git when LFS pointers are present; do not silently replace missing LFS objects with empty files.", "git lfs version", ["pull", "fetch", "checkout"]),
  def(imageKey, "repo", "vendored launcher (checksum pinned)", "deploy/vendor/gitcode-repo-py3", ["repo"], "Initialize and synchronize the OpenHarmony manifest repository.", "Use repo for the manifest-driven source tree; use git directly for a standalone repository.", "repo --version", ["init", "sync", "--manifest-url", "--manifest-branch", "-j"]),
  def(imageKey, "python3-requests", "snapshot (Python package provided by image)", `agent-harness/${test ? "openharmony-test" : imageKey.includes("fuzz") ? "openharmony-fuzz" : "openharmony-audit"}-runtime.json#/apt.python3-requests`, ["python3"], "Run repo and OpenHarmony helper code that imports requests.", "Use it as the declared helper dependency; do not treat an HTTP response as source evidence without retaining provenance.", "python3 -c 'import requests; print(requests.__version__)'", ["-c", "script path"], { kind: "library" }),
  def(imageKey, "build-essential", "snapshot (exact apt version not pinned)", `agent-harness/${test ? "openharmony-test" : imageKey.includes("fuzz") ? "openharmony-fuzz" : "openharmony-audit"}-runtime.json#/apt.build-essential`, ["cc", "gcc", "c++", "g++", "make"], "Build a supplied OpenHarmony component or a small verification harness with complete flags.", "Use the project build wrapper and declared product context; do not infer source safety from a successful build.", "cc -Wall -Wextra -o sample sample.c", ["-I", "-D", "-L", "-l", "-o"]),
  def(imageKey, "ccache", "snapshot (exact apt version not pinned)", `agent-harness/${test ? "openharmony-test" : imageKey.includes("fuzz") ? "openharmony-fuzz" : "openharmony-audit"}-runtime.json#/apt.ccache`, ["ccache"], "Cache repeatable compiler outputs during a bounded build.", "Use only for speed; retain compiler flags and invalidate cache when source/toolchain changes.", "ccache --version", ["--show-stats", "--zero-stats"]),
  def(imageKey, "cmake", "snapshot (exact apt version not pinned)", `agent-harness/${test ? "openharmony-test" : imageKey.includes("fuzz") ? "openharmony-fuzz" : "openharmony-audit"}-runtime.json#/apt.cmake`, ["cmake"], "Configure a CMake component or harness.", "Use when the component declares CMake; prefer the image build wrapper for the OpenHarmony tree.", "cmake -S . -B build", ["-S", "-B", "-D", "--build"]),
  def(imageKey, "ninja", "snapshot (exact apt version not pinned)", `agent-harness/${test ? "openharmony-test" : imageKey.includes("fuzz") ? "openharmony-fuzz" : "openharmony-audit"}-runtime.json#/apt.ninja-build`, ["ninja"], "Build a generated Ninja graph.", "Use when the selected build system emits build.ninja.", "ninja -C build target", ["-C", "-j"]),
  def(imageKey, "ssh-rsync-patch", "snapshot (exact apt versions not pinned)", `agent-harness/${test ? "openharmony-test" : imageKey.includes("fuzz") ? "openharmony-fuzz" : "openharmony-audit"}-runtime.json#/apt.ssh-rsync-patch`, ["ssh", "rsync", "patch"], "Transfer or apply explicitly scoped source data and patches.", "Use only with authorized endpoints and a recorded patch; use rsync for bounded local transfer.", "patch --dry-run -p1 < change.patch", ["-p", "--dry-run", "--delete"]),
  ...(test ? [] : [def(imageKey, "pkg-config", "snapshot (exact apt version not pinned)", `agent-harness/${imageKey.includes("fuzz") ? "openharmony-fuzz" : "openharmony-audit"}-runtime.json#/apt.pkg-config`, ["pkg-config"], "Resolve native compiler and linker flags declared by an OpenHarmony component.", "Use it when the build metadata provides a pkg-config module; preserve the reported version and flags.", "pkg-config --cflags --libs module", ["--cflags", "--libs", "--modversion"])]),
  wrapper(imageKey, "openharmony-init.sh", ["/opt/deepsonar/bin/openharmony-init.sh"], "deploy/openharmony-init.sh", "Initialize and synchronize a declared OpenHarmony manifest and branch.", "Use before build or audit when the source tree is not already present; preserve manifest URL and revision.", "/opt/deepsonar/bin/openharmony-init.sh --source-dir /workspace/openharmony --manifest-url URL --manifest-branch master", ["--source-dir", "--manifest-url", "--manifest-branch", "--manifest-file", "--group", "--jobs"]),
  wrapper(imageKey, "openharmony-build.sh", ["/opt/deepsonar/bin/openharmony-build.sh"], "deploy/openharmony-build.sh", "Build a named OpenHarmony product from a prepared source tree.", "Use after init and only with the product name and source revision required by the task.", "/opt/deepsonar/bin/openharmony-build.sh --source-dir /workspace/openharmony --product-name rk3568", ["--source-dir", "--product-name"])
];
const ohTestDefs = (imageKey) => [
  def(imageKey, "hdc", "3.2.0b; SDK 6.0.0.47", "agent-harness/openharmony-test-runtime.json#/downloads.hdc", ["hdc"], "Observe and operate an attached OpenHarmony device through the official hdc protocol.", "Use hdc for device behavior and installation; use HAP static inspection when no device is available.", "hdc list targets", ["list targets", "shell", "file send", "file recv", "install", "hilog", "fport", "tconn"], { prerequisites: ["Official hdc and libusb companion", "Authorized device", "USB/network transport", "On arm64, qemu-user-static and amd64 runtime libraries"], failure_handling: { normal_empty: "No targets is a normal empty observation; classify it as inconclusive/needs_human only when device evidence is required.", missing_condition: "No target, missing authorization, or unavailable transport is a missing runtime condition; do not fabricate device output." }, version_limits_side_effects_cleanup: "Official Linux x64 hdc is native on amd64 and uses qemu-user-static on arm64. Device state changes can have side effects; retain command, target identity, and logs, then remove transferred temporary files." }),
  wrapper(imageKey, "openharmony-hdc-bin.sh", ["/opt/deepsonar/bin/hdc"], "deploy/openharmony-hdc-bin.sh", "Provide the official hdc binary with the image's library path and arm64 qemu behavior.", "Use through the hdc wrapper or direct hdc commands after target preflight.", "/opt/deepsonar/bin/hdc version", ["version", "-v"]),
  wrapper(imageKey, "openharmony-env.sh", ["/opt/deepsonar/bin/openharmony-env.sh --check", "/opt/deepsonar/bin/openharmony-env.sh --check --hdc"], "deploy/openharmony-env.sh", "Verify source/build tools, hdc, and the runtime manifest.", "Use as a preflight; it does not verify a product build or device finding.", "/opt/deepsonar/bin/openharmony-env.sh --check --hdc", ["--check", "--hdc"]),
  wrapper(imageKey, "openharmony-hdc.sh", ["/opt/deepsonar/bin/openharmony-hdc.sh targets", "/opt/deepsonar/bin/openharmony-hdc.sh -- shell id"], "deploy/openharmony-hdc.sh", "Apply governed target listing and hdc passthrough with explicit no-target handling.", "Use this wrapper to preserve manifest and no-device semantics; do not bypass it for evidence-producing device actions.", "/opt/deepsonar/bin/openharmony-hdc.sh targets", ["targets", "--", "shell", "file", "install"], { failure_handling: { normal_empty: "targets with no rows is an empty device observation; preserve the wrapper's no-target classification." } }),
  capability(imageKey, "hdc-device-operations", "3.2.0b", "deploy/Dockerfile.agent-openharmony#inline manifest", ["/opt/deepsonar/bin/openharmony-hdc.sh"], "List targets, execute shell observations, transfer files, install packages, read hilog, and inspect ports/connections.", "Choose the smallest operation that answers the task; use static HAP evidence when runtime access is unavailable.", "openharmony-hdc.sh targets -> openharmony-hdc.sh -- shell id", ["targets", "shell", "file send", "file recv", "install", "hilog", "fport", "tconn"], { prerequisites: ["Authorized target and explicit operation permission"], composition_flow: "targets -> operation -> saved stdout/stderr/log -> Fact with target identity and timestamp." })
];
images.push(makeImage("deepsonar-openharmony-test", ["agent-harness/openharmony-test-runtime.json", "deploy/Dockerfile.agent-openharmony", "deploy/openharmony-env.sh", "deploy/openharmony-hdc.sh", "deploy/openharmony-hdc-bin.sh", "deploy/openharmony-init.sh", "deploy/openharmony-build.sh"], ["deepsonar-base"], [...commonBase("deepsonar-openharmony-test"), ...ohCommon("deepsonar-openharmony-test", true), ...ohTestDefs("deepsonar-openharmony-test")], ["inherited base tools", "OpenHarmony source sync/build", "hdc device protocol"]));

const ohAuditDefs = (imageKey) => [
  def(imageKey, "clang-audit-toolchain", "snapshot (exact versions not pinned)", "agent-harness/openharmony-audit-runtime.json#/apt.clang", ["clang", "clang++", "clang-tidy", "scan-build", "llvm-symbolizer"], "Run compiler-aware OpenHarmony source checks with compile_commands.json.", "Use clang-tidy/scan-build with build context; use cppcheck/sparse for complementary static views.", "clang-tidy -p build src/file.cpp", ["-p", "-checks", "--header-filter", "--status-bugs", "--use-analyzer"]),
  def(imageKey, "cppcheck", "snapshot (exact version not pinned)", "agent-harness/openharmony-audit-runtime.json#/apt.cppcheck", ["cppcheck"], "Run the declared lightweight C/C++ dataflow checks over a bounded source set.", "Use it as a complementary static observation; compiler-aware tools better model project flags.", "cppcheck --enable=warning,style --project=compile_commands.json", ["--project", "--enable", "--inconclusive", "--xml", "-I"]),
  def(imageKey, "sparse", "snapshot (exact version not pinned)", "agent-harness/openharmony-audit-runtime.json#/apt.sparse", ["sparse"], "Run Linux kernel style sparse checks when the source and compiler flags support it.", "Use only for code compatible with sparse; an unsupported codebase is a missing condition.", "sparse --version", ["-W", "-I", "-D"]),
  def(imageKey, "bear", "snapshot (exact version not pinned)", "agent-harness/openharmony-audit-runtime.json#/apt.bear", ["bear"], "Capture a compile_commands.json database around a supported build command.", "Use bear when the build system does not already emit compile commands; do not mix databases from different revisions.", "bear -- cmake --build build", ["--", "--append", "--output"]),
  def(imageKey, "gdb", "snapshot (exact version not pinned)", "agent-harness/openharmony-audit-runtime.json#/apt.gdb", ["gdb"], "Inspect a reproducible native crash or test process with symbols.", "Use gdb for controlled reproduction and stack inspection; it cannot prove a bug without a valid reproducer.", "gdb -q --batch -ex 'bt' --args ./program", ["-q", "--batch", "-ex", "--args"]),
  def(imageKey, "native-symbol-tools", "snapshot (exact versions not pinned)", "agent-harness/openharmony-audit-runtime.json#/apt.binutils", ["objdump", "addr2line"], "Map native addresses and inspect object metadata.", "Use after a compiler or runtime observation; preserve binary and debug symbol identity.", "addr2line -e target 0xADDRESS", ["-e", "-f", "-C", "-i"]),
  def(imageKey, "sanitizer-runtimes", "snapshot (exact versions not pinned)", "agent-harness/openharmony-audit-runtime.json#/apt.libasan", ["clang"], "Build a small ASan/UBSan verification harness or reproduce a supplied native issue.", "Use only with a valid harness and complete build context; sanitizer output is runtime evidence for that execution.", "clang -fsanitize=address,undefined -g -o sample sample.c", ["-fsanitize", "-g", "-fno-omit-frame-pointer"], { kind: "runtime_dependency", covers: ["compiler-rt", "libasan", "libubsan", "liblsan"] }),
  capability(imageKey, "openharmony-source-audit", "image toolchain snapshot", "deploy/Dockerfile.agent-openharmony-audit#inline manifest", ["openharmony-audit-scan.sh"], "Run the declared tidy, cppcheck, sparse, or combined source audit modes.", "Select a mode based on available compile context and the claim being tested; keep independent tool results separate.", "openharmony-audit-scan.sh --source-dir /workspace/oh --mode all --jobs 4", ["--source-dir", "--path", "--build-dir", "--mode", "--jobs"], { prerequisites: ["Source tree", "Optional compile_commands.json/build directory for compiler-aware modes", "Writable /workspace/oh-audit-out"], composition_flow: "source/build context -> selected static tools -> per-tool logs in /workspace/oh-audit-out -> normalized evidence." }),
  wrapper(imageKey, "openharmony-audit-env.sh", ["/opt/deepsonar/bin/openharmony-audit-env.sh --check"], "deploy/openharmony-audit-env.sh", "Verify the audit toolchain and sanitizer smoke prerequisites.", "Run before an audit; missing tools make the corresponding result inconclusive.", "/opt/deepsonar/bin/openharmony-audit-env.sh --check", ["--check"]),
  wrapper(imageKey, "openharmony-audit-scan.sh", ["/opt/deepsonar/bin/openharmony-audit-scan.sh"], "deploy/openharmony-audit-scan.sh", "Run bounded OpenHarmony static audit modes and write separate logs.", "Use the wrapper to keep output paths and mode selection explicit.", "/opt/deepsonar/bin/openharmony-audit-scan.sh --source-dir /workspace/oh --mode tidy --jobs 4", ["--path", "--source-dir", "--build-dir", "--mode", "--jobs"], { kind: "wrapper" })
];
images.push(makeImage("deepsonar-openharmony-audit", ["agent-harness/openharmony-audit-runtime.json", "deploy/Dockerfile.agent-openharmony-audit", "deploy/openharmony-audit-env.sh", "deploy/openharmony-audit-scan.sh", "deploy/openharmony-init.sh", "deploy/openharmony-build.sh"], ["deepsonar-base"], [...commonBase("deepsonar-openharmony-audit"), ...ohCommon("deepsonar-openharmony-audit"), ...ohAuditDefs("deepsonar-openharmony-audit")], ["inherited base tools", "OpenHarmony source sync/build", "Clang/static analysis", "sanitizer and native evidence"]));

const ohFuzzDefs = (imageKey) => [
  def(imageKey, "clang-fuzz-toolchain", "snapshot (exact versions not pinned)", "agent-harness/openharmony-fuzz-runtime.json#/apt.clang", ["clang", "clang++", "llvm-symbolizer"], "Compile an OpenHarmony or native fuzz harness with sanitizer instrumentation.", "Use the declared compiler/runtime; retain flags and source revision.", "clang++ -fsanitize=fuzzer,address -o harness harness.cc", ["-fsanitize", "-fno-omit-frame-pointer", "-g", "-o"]),
  def(imageKey, "compiler-rt-sanitizers", "snapshot (exact versions not pinned)", "agent-harness/openharmony-fuzz-runtime.json#/apt.compiler-rt", ["clang"], "Provide compiler-rt, ASan, UBSan, and LSan runtimes for instrumented execution.", "Use only via the matching compiler and target; runtime output is tied to that instrumentation.", "clang -fsanitize=address,undefined -o sample sample.c", ["-fsanitize", "-g", "-fno-omit-frame-pointer"], { kind: "runtime_dependency", covers: ["compiler-rt", "libasan", "libubsan", "liblsan"] }),
  def(imageKey, "libFuzzer", "snapshot (exact version not pinned)", "agent-harness/openharmony-fuzz-runtime.json#/apt.libfuzzer", [], "Run an in-process harness with a bounded seed corpus.", "Use libFuzzer for in-process targets; use AFL++ for forkserver workflows.", "harness -runs=1 corpus/seed", ["-runs", "-max_total_time", "-artifact_prefix", "-timeout"], { kind: "runtime_dependency" }),
  def(imageKey, "AFL++", "snapshot (exact version not pinned)", "agent-harness/openharmony-fuzz-runtime.json#/apt.afl++", ["afl-fuzz", "afl-clang-fast"], "Run an AFL++ target with explicit corpus and output directories.", "Choose AFL++ when forkserver/corpus behavior fits the harness; do not mix corpus formats silently.", "afl-fuzz -i corpus/in -o corpus/out -- ./harness @@", ["-i", "-o", "-t", "-m", "-M", "-S"]),
  def(imageKey, "gdb", "snapshot (exact version not pinned)", "agent-harness/openharmony-fuzz-runtime.json#/apt.gdb", ["gdb"], "Inspect a reproduced native fuzz crash with a stable binary and symbols.", "Use only after retaining the crashing input and matching binary.", "gdb -q --batch -ex 'bt' --args ./harness crash.input", ["-q", "--batch", "-ex", "--args"]),
  def(imageKey, "native-symbol-tools", "snapshot (exact versions not pinned)", "agent-harness/openharmony-fuzz-runtime.json#/apt.binutils", ["objdump", "readelf", "addr2line"], "Confirm architecture and symbolize a fuzz crash artifact.", "Use before interpreting sanitizer stacks; preserve binary and symbol hashes.", "readelf -hW harness", ["-h", "-S", "-s", "-e", "-f", "-C"]),
  capability(imageKey, "openharmony-fuzz-build", "image compiler/runtime snapshot", "deploy/Dockerfile.agent-openharmony-fuzz#inline manifest", ["openharmony-fuzz-build.sh"], "Build a libFuzzer or AFL++ harness with explicit source, engine, and output.", "Select the engine based on harness compatibility and desired corpus workflow.", "openharmony-fuzz-build.sh --source harness.cc --engine libfuzzer --output /workspace/harness", ["--source", "--engine", "--output", "--cflags", "--ldflags"], { prerequisites: ["Harness source", "Matching compiler/runtime", "Writable output path"] }),
  wrapper(imageKey, "openharmony-fuzz-env.sh", ["/opt/deepsonar/bin/openharmony-fuzz-env.sh --check", "/opt/deepsonar/bin/openharmony-fuzz-env.sh --check --static"], "deploy/openharmony-fuzz-env.sh", "Verify fuzzer, symbolizer, sanitizer, and static/dynamic architecture prerequisites.", "Run before building or running a fuzz target.", "/opt/deepsonar/bin/openharmony-fuzz-env.sh --check --static", ["--check", "--static"]),
  wrapper(imageKey, "openharmony-fuzz-build.sh", ["/opt/deepsonar/bin/openharmony-fuzz-build.sh"], "deploy/openharmony-fuzz-build.sh", "Compile a bounded OpenHarmony fuzz harness with libFuzzer or AFL++.", "Use after the source and engine are selected.", "/opt/deepsonar/bin/openharmony-fuzz-build.sh --source harness.cc --engine afl --output /workspace/harness", ["--source", "--engine", "--output", "--cflags", "--ldflags"], { kind: "wrapper" })
];
images.push(makeImage("deepsonar-openharmony-fuzz", ["agent-harness/openharmony-fuzz-runtime.json", "deploy/Dockerfile.agent-openharmony-fuzz", "deploy/openharmony-fuzz-env.sh", "deploy/openharmony-fuzz-build.sh", "deploy/openharmony-init.sh", "deploy/openharmony-build.sh"], ["deepsonar-base"], [...commonBase("deepsonar-openharmony-fuzz"), ...ohCommon("deepsonar-openharmony-fuzz"), ...ohFuzzDefs("deepsonar-openharmony-fuzz")], ["inherited base tools", "OpenHarmony source sync/build", "libFuzzer/AFL++", "sanitizer and crash reproduction"]));

const mobileDefs = (imageKey) => [
  def(imageKey, "java", "17.0.19+10", "agent-harness/mobile-runtime.json#/downloads.jdk", ["java", "javac", "jar"], "Run Java based Android analysis tools and inspect Java package metadata.", "Use the image JDK for JADX/apktool/bundletool; do not substitute an unpinned host JDK.", "java -version", ["-version", "-jar", "-cp", "--release"]),
  def(imageKey, "uv", "0.11.32", "agent-harness/mobile-runtime.json#/downloads.uv", ["uv"], "Create or select the image's managed Python environment for mobile analysis packages.", "Use uv only with the declared offline package set and Python version; do not download arbitrary packages during a job.", "uv --version", ["python", "venv", "pip", "--offline"]),
  def(imageKey, "python3.12", "3.12.13", "agent-harness/mobile-runtime.json#/managed.python.versions[0]", ["/opt/deepsonar/python/3.12.13/bin/python", "/opt/deepsonar/mobile-venv/bin/python"], "Run the pinned Python environment used by Frida, Objection, androguard, droidasc, and LIEF.", "Use the mobile venv for installed Python packages; the inherited python3 is a different base runtime.", "/opt/deepsonar/mobile-venv/bin/python --version", ["-m", "-c", "script path"]),
  def(imageKey, "jadx", "1.5.6", "agent-harness/mobile-runtime.json#/downloads.jadx", ["jadx"], "Search or view a more complete Java/Kotlin decompilation of an APK when cross-reference context matters.", "Choose JADX for broad decompilation and navigation; choose droidasc for targeted large-APK queries and lower output volume.", "jadx --output-dir /workspace/jadx-out sample.apk", ["--output-dir", "--threads-count", "--deobf", "--show-bad-code"]),
  def(imageKey, "droidasc", "0.1.1.post1", "agent-harness/mobile-runtime.json#/managed.pip.droidasc", ["droidasc"], "Query classes, manifest data, and references in a large APK without materializing a full decompilation.", "Prefer droidasc for targeted lookup and reference queries; use JADX when complete source-like views are needed. The pinned CLI exposes getmanifest, getclass, and findrefs; do not use its GUI mode.", "droidasc getmanifest app.apk -o AndroidManifest.xml; droidasc getclass app.apk 'Lcom/poc/Main;' -o Main.java --threads 16; droidasc findrefs app.apk string token -o string_refs.txt", ["getmanifest APK [-o FILE]", "getclass APK CLASS [-o FILE] [--threads N]", "findrefs APK {string,type,method,field} TERM [--class NAME] [--fuzzy-class] [-o FILE]"], { output_interpretation: "getmanifest writes decoded AndroidManifest.xml; getclass writes source-like code for one class; findrefs reports matching string/type/method/field references across DEX entries. A no-match result is scoped to the queried APK and term and does not prove absence of behavior.", composition_flow: "file/hash app.apk -> getmanifest -> findrefs for a narrow term -> getclass for the relevant class -> JADX/apktool for broader or resource-aware confirmation.", evidence_retention: ["APK SHA-256", "droidasc version", "subcommand and query type/term", "class filter and fuzzy flag", "output files and hashes", "stdout/stderr", "exit code"], version_limits_side_effects_cleanup: "Droid ASC 0.1.1.post1 is on-demand and read-only for the APK; it is not a runtime/device observation and does not replace full decompilation. Do not pass --gui in the Agent image. Keep this catalog version synchronized with the image's runtime source pin.", verification_note: "Catalog follows the intended droidasc 0.1.1.post1 release; synchronize agent-harness/mobile-runtime.json and the Dockerfile pin before merge." }),
  def(imageKey, "apktool", "3.0.3", "agent-harness/mobile-runtime.json#/downloads.apktool", ["apktool"], "Decode APK resources, manifest, and smali, or rebuild a modified package for a controlled test.", "Choose apktool for resources/smali and package structure; use JADX for Java/Kotlin view and droidasc for targeted queries.", "apktool d --output /workspace/apktool-out sample.apk", ["d", "b", "--output", "--frame-path", "--use-aapt2"]),
  def(imageKey, "bundletool", "1.18.3", "agent-harness/mobile-runtime.json#/downloads.bundletool", ["bundletool"], "Inspect or build Android App Bundles and derive APK sets with bundle-aware semantics.", "Use bundletool for AAB/APKS workflows; use apktool/JADX only after obtaining the relevant APK.", "bundletool version", ["build-apks", "extract-apks", "dump", "--bundle", "--apks", "--output"]),
  def(imageKey, "apkeep", "1.0.0", "agent-harness/mobile-runtime.json#/downloads.apkeep", ["apkeep"], "Retrieve or normalize an APK from an explicitly permitted package source.", "Use only when acquisition is part of the task and provenance/network policy permits it; do not treat a downloaded APK as trusted input.", "apkeep --help", ["package id", "source", "output", "architecture"]),
  def(imageKey, "androguard", "4.1.4", "agent-harness/mobile-runtime.json#/managed.pip.androguard", ["androguard"], "Perform Python-based APK/Dex/manifest inspection when programmatic analysis is needed.", "Use androguard for structured Python analysis; use droidasc/JADX for faster targeted or source-like exploration.", "androguard --help", ["APK path", "DEX path", "output format"]),
  def(imageKey, "apkcheckpack", "20260618", "agent-harness/mobile-runtime.json#/downloads.apkcheckpack", ["apkcheckpack", "/opt/deepsonar/bin/apkcheckpack"], "Run the official package integrity or compatibility check on an Android package.", "Use for the declared checker result; do not replace it with a generic signature or lint command.", "apkcheckpack -h", ["input APK", "output", "check mode"]),
  def(imageKey, "adb", "platform-tools 36.0.0", "agent-harness/mobile-runtime.json#/downloads.platform-tools", ["adb"], "Observe and operate an attached Android device or emulator.", "Use ADB for Android device state and logs; use Frida for in-process instrumentation and static tools for package evidence.", "adb devices", ["devices", "shell", "logcat", "pull", "push", "install", "forward"], { prerequisites: ["Authorized Android target", "ADB transport", "Explicit device operation permission"], failure_handling: { normal_empty: "adb devices with no rows is a normal empty observation; classify as inconclusive/needs_human only when device evidence is required.", missing_condition: "No device, unauthorized device, or transport failure is a missing condition; preserve adb stderr and do not invent runtime behavior." } }),
  def(imageKey, "hdc", "3.2.0b; SDK 6.0.0.47", "agent-harness/mobile-runtime.json#/downloads.hdc", ["hdc"], "Observe an attached OpenHarmony device or install/inspect a HAP through the official hdc protocol.", "Use hdc for OpenHarmony device behavior; use mobile-hap.sh for static HAP inspection without a device.", "hdc list targets", ["list targets", "shell", "file send", "file recv", "install", "hilog", "fport", "tconn"], { prerequisites: ["Authorized OpenHarmony target", "Official hdc binary and libusb companion", "On arm64, qemu-user-static for x64 hdc"], failure_handling: { normal_empty: "No hdc targets is an empty device observation.", missing_condition: "No target or authorization is a missing condition; report inconclusive/needs_human when runtime evidence is required." } }),
  def(imageKey, "frida", "frida-tools 14.10.4; Frida runtime 17.17.0", "agent-harness/mobile-runtime.json#/managed.pip.frida-tools + agent-harness/mobile-runtime.json#/managed.pip.frida", ["frida"], "Observe or instrument live Android processes when static evidence cannot answer behavior questions.", "Use Frida for in-process runtime observation; use ADB for transport/logs and Objection for higher-level workflows. Mark every Frida operation device_required.", "frida -U -f com.example.app -l /workspace/hook.js --no-pause  # spawn; use -n com.example.app to attach", ["--version", "-U", "-f PACKAGE", "-n PROCESS", "-l SCRIPT", "--no-pause"], { device_required: true, prerequisites: ["Compatible Frida server on the target", "Root or required process permissions", "Authorized Android device and USB/network transport", "A reviewed hook script"], output_interpretation: "Script messages, return values, and process termination are observations from the selected process and time. A successful attach proves only that the process was reachable; it does not prove a path was exercised unless the script records it.", composition_flow: "mobile-adb.sh devices -> verify Frida server/ABI -> frida -U -f PACKAGE or -n PROCESS -l SCRIPT -> save messages and target logs -> detach/kill and clean temporary script.", failure_handling: { normal_empty: "No matching process or no emitted messages is an empty observation; record the process selector and script behavior.", missing_condition: "Missing server, device, permission, process, or ABI is a missing condition; do not claim a hook ran.", transient_retryable: "If USB/transport or process startup races, retain the first stderr/log and retry once within budget after checking for a duplicate spawn." }, evidence_retention: ["Frida and server versions", "device serial and ABI", "target package/process", "script hash and contents", "spawn/attach command", "captured messages and logcat", "cleanup result"] }),
  def(imageKey, "frida-tools", "14.10.4", "agent-harness/mobile-runtime.json#/managed.pip.frida-tools", ["frida"], "Provide the Frida CLI used to attach to or spawn an authorized Android process.", "Use the CLI with the matching Frida Python/server version; use Objection for its higher-level workflow.", "frida -U -n com.example.app -l /workspace/hook.js --no-pause", ["-U", "-f PACKAGE", "-n PROCESS", "-l SCRIPT", "--no-pause"], { device_required: true, prerequisites: ["Frida runtime and compatible target server", "Authorized device/process"], output_interpretation: "CLI output is the transport and script observation; a zero exit code does not prove the hook observed the intended path.", composition_flow: "ADB device check -> Frida server check -> attach/spawn -> capture -> detach/cleanup.", evidence_retention: ["CLI version", "server version", "target identity", "script hash", "full command", "stdout/stderr", "exit code"] }),
  def(imageKey, "frida-server", "17.17.0", "agent-harness/mobile-runtime.json#/downloads.frida-server", ["/opt/deepsonar/frida-server/frida-server-android-arm", "/opt/deepsonar/frida-server/frida-server-android-arm64", "/opt/deepsonar/frida-server/frida-server-android-x86_64"], "Select and transfer the Frida server matching the authorized Android target ABI.", "Use only the matching official server; do not run an ABI-incompatible server or claim runtime evidence without confirming its process.", "adb push /opt/deepsonar/frida-server/frida-server-android-arm64 /data/local/tmp/frida-server", ["target ABI", "adb push", "remote path", "chmod", "server arguments"], { device_required: true, prerequisites: ["Authorized rooted or permitted Android target", "ADB transport", "Matching server ABI"], output_interpretation: "The server process and version establish instrumentation readiness; they do not establish that a target method executed.", composition_flow: "adb devices -> select ABI -> adb push server -> start server -> frida attach/spawn -> stop server and remove remote file.", evidence_retention: ["server file hash", "device ABI/serial", "push/start/stop commands", "server log", "cleanup result"], version_limits_side_effects_cleanup: "Frida server is a device-side companion. Starting it changes device process state; stop it and remove the transferred file after the observation." }),
  def(imageKey, "objection", "1.12.5", "agent-harness/mobile-runtime.json#/managed.pip.objection", ["objection"], "Use a guided Frida-based runtime workflow for an authorized mobile process.", "Use Objection for its supported high-level commands; use raw Frida when exact hook behavior or script provenance matters.", "objection version", ["-g", "explore", "run", "plugin"], { prerequisites: ["Compatible Frida server", "Authorized process/device", "Explicit runtime permission"] }),
  def(imageKey, "native-binutils", "apt package (version not pinned in mobile source)", "agent-harness/mobile-runtime.json#/apt.binutils", ["readelf", "objdump", "nm", "file"], "Inspect native .so architecture, sections, symbols, imports, and strings.", "Use binutils for deterministic metadata; choose radare2/LIEF for deeper structural queries.", "readelf -hW libnative.so", ["-h", "-S", "-s", "-d", "-W"]),
  def(imageKey, "radare2", "6.2.0", "agent-harness/mobile-runtime.json#/downloads.radare2", ["r2"], "Explore native control flow and symbols interactively or with bounded scripts.", "Use r2 for deeper native exploration after readelf/objdump identify the relevant architecture and sections.", "r2 -q -c 'iI;is' libnative.so", ["-q", "-c", "-A", "-2"]),
  def(imageKey, "lief", "1.0.0", "agent-harness/mobile-runtime.json#/managed.pip.lief", ["python3"], "Parse and edit native binary structures programmatically when a reproducible script is required.", "Use LIEF for structured programmatic parsing; preserve the original and record any mutation separately.", "python3 -c 'import lief; print(lief.__version__)'", ["-c", "binary path", "output path"]),
  def(imageKey, "libatomic1", "apt package (version not pinned in mobile source)", "agent-harness/mobile-runtime.json#/apt.libatomic1", [], "Provide the atomic runtime library required by the official device companion or native tooling.", "Implementation dependency; the Agent selects adb/hdc rather than this library.", "not directly callable", [], { kind: "implementation_dependency", agent_visible: false, implementation_only: true }),
  def(imageKey, "libimobiledevice-utils", "apt package (version not pinned in mobile source)", "agent-harness/mobile-runtime.json#/apt.libimobiledevice-utils", ["idevice_id"], "List and identify authorized iOS devices through usbmuxd.", "Use idevice_id for discovery; use ideviceinstaller for package operations and iproxy for port forwarding.", "idevice_id -l", ["-l", "-u"]),
  def(imageKey, "ideviceinstaller", "apt package (version not pinned in mobile source)", "agent-harness/mobile-runtime.json#/apt.ideviceinstaller", ["ideviceinstaller"], "Install, enumerate, or remove an application on an authorized physical iOS device.", "Use only for explicitly authorized device operations; static IPA inspection remains separate.", "ideviceinstaller -l", ["-l", "-i", "-U", "-u"]),
  def(imageKey, "libplist-utils", "apt package (version not pinned in mobile source)", "agent-harness/mobile-runtime.json#/apt.libplist-utils", ["plistutil"], "Decode or inspect plist data from an iOS artifact or device operation.", "Use plistutil for plist syntax; do not infer runtime state from a static plist alone.", "plistutil -i Info.plist -o -", ["-i", "-o", "-f"]),
  def(imageKey, "libusbmuxd-tools", "apt package (version not pinned in mobile source)", "agent-harness/mobile-runtime.json#/apt.libusbmuxd-tools", ["iproxy"], "Forward a local TCP port to an authorized iOS device service.", "Use only when a device service and port are explicitly required; retain the forwarding lifecycle.", "iproxy 2222 22 --udid DEVICE_UDID", ["local port", "device port", "--udid"]),
  def(imageKey, "iOS-host-tools", "apt package (versions not pinned in mobile source)", "agent-harness/mobile-runtime.json#/apt.libimobiledevice-utils", ["idevice_id", "ideviceinstaller", "plistutil", "iproxy"], "Observe or transfer data from an attached iOS device through Linux usbmuxd host tools.", "Use these for physical iOS host operations; Xcode, Simulator, IDA, Ghidra, and GUI tools are not present.", "idevice_id -l", ["-l", "-u", "-i", "-q", "--udid"], { prerequisites: ["Authorized iOS device", "usbmuxd transport", "Explicit device operation permission"], failure_handling: { normal_empty: "No listed device is an empty observation.", missing_condition: "No device, pairing, or usbmuxd condition is missing; report inconclusive/needs_human when device evidence is required." } }),
  wrapper(imageKey, "mobile-env.sh", ["/opt/deepsonar/bin/mobile-env.sh --check"], "deploy/mobile-env.sh", "Verify all mobile static, device, native, and Frida prerequisites and deliberate exclusions.", "Run before selecting a mobile workflow; it does not analyze an APK itself.", "/opt/deepsonar/bin/mobile-env.sh --check", ["--check"]),
  wrapper(imageKey, "mobile-adb.sh", ["/opt/deepsonar/bin/mobile-adb.sh --check", "/opt/deepsonar/bin/mobile-adb.sh"], "deploy/mobile-adb.sh", "Run ADB version and device preflight with no-target classification.", "Use before Android device operations.", "/opt/deepsonar/bin/mobile-adb.sh --check", ["--check"]),
  wrapper(imageKey, "mobile-hdc.sh", ["/opt/deepsonar/bin/mobile-hdc.sh --check", "/opt/deepsonar/bin/mobile-hdc.sh targets"], "deploy/mobile-hdc.sh", "Run hdc preflight, list targets, or pass through a governed OpenHarmony operation.", "Use before HAP device operations.", "/opt/deepsonar/bin/mobile-hdc.sh targets", ["--check", "targets", "--", "shell", "install"]),
  wrapper(imageKey, "mobile-ios.sh", ["/opt/deepsonar/bin/mobile-ios.sh --check", "/opt/deepsonar/bin/mobile-ios.sh devices"], "deploy/mobile-ios.sh", "Run iOS host-tool preflight and list attached devices.", "Use for physical iOS host operations; there is no Xcode or simulator workflow in this image.", "/opt/deepsonar/bin/mobile-ios.sh devices", ["--check", "devices", "--udid"]),
  wrapper(imageKey, "mobile-hap.sh", ["/opt/deepsonar/bin/mobile-hap.sh --check", "/opt/deepsonar/bin/mobile-hap.sh inspect sample.hap"], "deploy/mobile-hap.sh", "Inspect HAP archive structure, pack.info, module.json, module.json5, and config.json statically.", "Use for static HAP evidence; use hdc only when live device behavior is required.", "/opt/deepsonar/bin/mobile-hap.sh inspect sample.hap", ["--check", "inspect", "HAP path"], { failure_handling: { normal_empty: "An archive with no requested metadata is an empty static observation; retain the listing and report unsupported/missing metadata." } }),
  wrapper(imageKey, "mobile-so.sh", ["/opt/deepsonar/bin/mobile-so.sh --check", "/opt/deepsonar/bin/mobile-so.sh inspect libnative.so"], "deploy/mobile-so.sh", "Run lightweight .so identification with file/readelf/r2/LIEF.", "Use it for static native triage; use a deeper analyzer only when the triage evidence warrants it.", "/opt/deepsonar/bin/mobile-so.sh inspect libnative.so", ["--check", "inspect", "SO path"], { failure_handling: { normal_empty: "A stripped object may have no symbols; record that as a limit, not a clean bill of health." } }),
  wrapper(imageKey, "mobile-apkcheckpack-bin.sh", ["/opt/deepsonar/bin/apkcheckpack"], "deploy/mobile-apkcheckpack-bin.sh", "Provide the official ApkCheckPack binary with arm64 qemu handling.", "Use through apkcheckpack; preserve checker version and package hash.", "apkcheckpack -h", ["-h", "input APK", "output"]),
  capability(imageKey, "mobile-static-selection", "image pinned tool set", "deploy/Dockerfile.agent-mobile#inline manifest", ["droidasc", "jadx", "apktool", "bundletool", "androguard", "apkcheckpack"], "Choose targeted query, decompilation, resource/smali decode, bundle analysis, Python inspection, or official package checking based on the mobile artifact.", "droidasc for targeted large-APK queries; JADX for broad source-like view; apktool for resources/smali; bundletool for AAB/APKS; androguard for scripted Dex/manifest analysis; ApkCheckPack for its official check.", "file sample.apk -> droidasc/JADX/apktool/bundletool -> normalized artifact", ["APK/AAB/HAP path", "output directory", "package id", "query or mode"], { composition_flow: "file/unzip -> targeted analyzer -> optional broader view -> evidence with artifact hash and tool version." }),
  capability(imageKey, "mobile-device-selection", "adb/hdc/Frida/iOS host tool set", "deploy/Dockerfile.agent-mobile#inline manifest", ["adb", "hdc", "frida", "objection", "idevice_id", "ideviceinstaller", "iproxy"], "Choose Android ADB, OpenHarmony hdc, Frida/Objection, or iOS usbmuxd tools for live observation.", "ADB/hdc/iOS tools provide transport and device operations; Frida/Objection provide in-process behavior; static tools remain valid when no device exists.", "device preflight -> minimal operation -> saved log/artifact -> cleanup", ["device id", "operation", "timeout", "remote/local path"], { prerequisites: ["The relevant authorized device and protocol"], failure_handling: { normal_empty: "No device/process is an empty observation.", missing_condition: "No target, authorization, server, or transport is a missing condition and limits conclusions to static evidence." } }),
  capability(imageKey, "mobile-native-selection", "radare2 6.2.0 / LIEF 1.0.0 / binutils", "deploy/Dockerfile.agent-mobile#inline manifest", ["file", "readelf", "objdump", "nm", "r2", "python3"], "Analyze native .so files from fast metadata through deeper structural inspection.", "Start with file/readelf/objdump/nm; use r2 for interactive control-flow exploration and LIEF for scripted structures.", "file lib.so -> readelf -hW lib.so -> r2 -q -c 'iI' lib.so", ["input .so", "symbol/section query", "r2 command", "output path"]),
  capability(imageKey, "mobile-hap-device-boundary", "hdc 3.2.0b / SDK 6.0.0.47", "deploy/Dockerfile.agent-mobile#inline manifest", ["mobile-hap.sh", "mobile-hdc.sh"], "Keep static HAP package observations separate from live OpenHarmony device observations.", "Use mobile-hap.sh without a device; use mobile-hdc.sh only when a target and authorization are available.", "mobile-hap.sh inspect sample.hap -> mobile-hdc.sh targets", ["HAP path", "target", "operation"], { output_interpretation: "HAP metadata proves package contents at the captured hash; it does not prove installed or runtime behavior." })
];
images.push(makeImage("deepsonar-mobile", ["agent-harness/mobile-runtime.json", "deploy/Dockerfile.agent-mobile", "deploy/mobile-env.sh", "deploy/mobile-adb.sh", "deploy/mobile-hdc.sh", "deploy/mobile-ios.sh", "deploy/mobile-hap.sh", "deploy/mobile-so.sh", "deploy/mobile-apkcheckpack-bin.sh"], ["deepsonar-base"], [...commonBase("deepsonar-mobile"), ...mobileDefs("deepsonar-mobile")], ["inherited base tools", "Android package analysis", "Android/OpenHarmony/iOS device operations", "Frida/Objection", "native .so analysis"]));

const expectedImages = [
  "deepsonar-base", "deepsonar-audit", "deepsonar-kali-minimal",
  "deepsonar-chrome-test", "deepsonar-chrome-audit", "deepsonar-chrome-fuzz",
  "deepsonar-clickhouse-audit", "deepsonar-clickhouse-test", "deepsonar-clickhouse-fuzz",
  "deepsonar-openharmony-test", "deepsonar-openharmony-audit", "deepsonar-openharmony-fuzz",
  "deepsonar-mobile"
];
if (images.length !== expectedImages.length || expectedImages.some((key, i) => images[i].image_key !== key)) {
  throw new Error(`image coverage mismatch: expected ${expectedImages.length}, got ${images.length}`);
}
for (const image of images) {
  if (!image.self_contained || image.entries.length === 0) throw new Error(`${image.image_key} is not self-contained`);
  const ids = new Set();
  for (const e of image.entries) {
    if (ids.has(e.id)) throw new Error(`${image.image_key} has duplicate entry id ${e.id}`);
    ids.add(e.id);
    if (e.agent_visible && e.implementation_only) throw new Error(`${image.image_key}/${e.id} cannot be both agent-visible and implementation-only`);
    for (const field of ["image_key", "id", "kind", "version", "version_source", "commands", "usage_scenario", "selection_basis", "prerequisites", "minimal_invocation", "common_parameters", "output_interpretation", "failure_handling", "composition_flow", "evidence_retention", "version_limits_side_effects_cleanup", "verification_status"]) {
      if (e[field] === undefined || e[field] === null) throw new Error(`${image.image_key}/${e.id} missing ${field}`);
    }
    for (const category of Object.keys(FAILURE)) if (!(category in e.failure_handling)) throw new Error(`${image.image_key}/${e.id} missing failure category ${category}`);
  }
}

const catalog = {
  schema: "deepsonar.runtime-manual-catalog/v1",
  catalog_version: "2026-09-17",
  generated_by: "agent-harness/runtime-manuals/generate-catalog.mjs",
  delivery_path: "/opt/deepsonar/manuals",
  failure_categories: Object.keys(FAILURE),
  source_contracts: ["deploy/runtime-image-registry.json", "agent-harness/runtime-images.json", "agent-harness/*-runtime.json", "deploy/Dockerfile.agent*", "deploy/*-env.sh", "deploy/*-build.sh", "deploy/*-scan.sh", "deploy/*-smoke.sh"],
  images,
  totals: {
    image_count: images.length,
    entry_count: images.reduce((n, image) => n + image.entry_count, 0),
    agent_visible_entry_count: images.reduce((n, image) => n + image.agent_visible_entry_count, 0),
    implementation_only_entry_count: images.reduce((n, image) => n + image.implementation_only_entry_count, 0)
  }
};

fs.writeFileSync(path.join(here, "catalog.json"), `${JSON.stringify(catalog, null, 2)}\n`, "utf8");
console.log(JSON.stringify(catalog.totals));
