/**
 * Phase-0 characterization manifest for the Scheduler registrar and OpenAPI
 * document.  Keep method/path pairs stable while splitting bounded contexts;
 * a registrar move must update the manifest only when the API surface is
 * intentionally changed.
 */

export const REGISTERED_ROUTE_SURFACE = `
DELETE /agent-roles/:id
DELETE /credentials/:id
DELETE /exports/:id
DELETE /findings/:id/comments/:commentId
DELETE /findings/:id/links/:linkId
DELETE /gateway/*
DELETE /imports/:id
DELETE /projects/:id/integrations/plane
DELETE /projects/:id/role-configs/:roleId
DELETE /skill-sources/:id
DELETE /tasks/:canvasId
GET /agent-roles
GET /audit-logs
GET /auth/me
GET /auth/status
GET /canvases/:id
GET /canvases/:id/broadcasts
GET /canvases/:id/messages
GET /canvases/:id/convergence
GET /control/v1/jobs/:jobId/capabilities
GET /control/v1/jobs/:jobId/agent/capabilities_list
GET /control/v1/jobs/:jobId/openapi.json
GET /control/v1/jobs/:jobId/operations/:operationId
GET /canvases/:id/delta
GET /canvases/:id/facts
GET /canvases/:id/facts/:nodeId
GET /canvases/:id/nodes/:nodeId
GET /canvases/:id/report
GET /canvases/:id/report/availability
GET /canvases/:id/reports
GET /canvases/:id/summary
GET /credentials
GET /credentials/:id
GET /credentials/:id/compatibility
GET /credentials/:id/impact
GET /credentials/:id/models
GET /credentials/providers
GET /exports/:id
GET /exports/:id/download
GET /findings
GET /findings/:id
GET /findings/:id/report
GET /findings/:id/shared-assets
GET /gateway/*
GET /global-settings
GET /health
GET /imports/:id
GET /jobs
GET /jobs/:id
GET /jobs/:id/events
GET /jobs/:id/evidence
GET /jobs/:id/evidence/session
GET /jobs/:id/evidence/session/download
GET /jobs/:id/evidence/stream
GET /metrics
GET /openapi.json
GET /plane-info
GET /platform/exports
GET /platform/shared-assets
GET /projects
GET /projects/:id
GET /projects/:id/canvas
GET /projects/:id/canvases
GET /projects/:id/exports
GET /projects/:id/readiness
GET /projects/:id/role-configs
GET /projects/:id/roles
GET /projects/:id/settings
GET /projects/:id/shared-assets
GET /projects/:id/shared-assets/policy
GET /readiness
GET /reports/:id/markdown
GET /reports/:id/sarif
GET /role-configs/bindable
GET /role-configs/global
PATCH /role-configs/:id/agent-cli
PATCH /role-configs/:id/runtime-image
GET /runtime-images
GET /runtime-images/:id([0-9a-fA-F-]{36})
GET /runtime-images/registry
GET /runtime-images/registry/pull-status
GET /runtime-image-versions/:id/usage
GET /schema
GET /schema.md
GET /shared-assets/:id/content
GET /skill-sources
GET /skill-sources/:id
GET /terminal-ws
GET /tokens
GET /users
GET /ws
PATCH /agent-roles/:id
PATCH /canvases/:id/facts/:nodeId/verification
PATCH /credentials/:id
PATCH /findings/:id/disposition
PATCH /findings/:id/verify-status
PATCH /gateway/*
PATCH /global-settings
PATCH /jobs/:id/priority
PATCH /projects/:id
PATCH /projects/:id/settings
PATCH /projects/:id/shared-assets/policy
PATCH /runtime-images/registry/channel
PATCH /users/:id
POST /agent-roles
POST /auth/bootstrap
POST /auth/change-password
POST /auth/change-username
POST /auth/login
POST /auth/logout
POST /auth/ws-ticket
POST /canvases/:id/convergence/drain-priority
POST /canvases/:id/convergence/pause
POST /canvases/:id/convergence/resume
POST /canvases/:id/convergence/run-hub-now
POST /canvases/:id/convergence/stop-after-gate
POST /canvases/:id/messages
POST /control/v1/jobs/:jobId/operations/:operationId
POST /canvases/:id/jobs/cancel-active
POST /canvases/:id/report/retry
POST /canvases/:id/report/refresh
POST /credentials
POST /credentials/:id/models
POST /credentials/models/preview
POST /credentials/:id/rotate
POST /credentials/:id/status
POST /credentials/:id/test
POST /credentials/batch-bind
POST /exports/:id/cancel
POST /findings/:id/comments
POST /findings/:id/evidence-jobs
POST /findings/:id/links
POST /findings/:id/report
POST /findings/:id/verify
POST /findings/:id/shared-assets
POST /gateway/*
POST /imports
POST /imports/:id/apply
POST /imports/:id/cancel
POST /imports/:id/preview
POST /jobs
POST /jobs/:id/cancel
POST /jobs/:id/resume
POST /jobs/:id/rerun-current
POST /platform/exports
POST /platform/shared-assets
POST /projects
POST /projects/:id/archive
POST /projects/:id/events
POST /projects/:id/exports
POST /projects/:id/integrations/plane/sync
POST /projects/:id/shared-assets
POST /projects/:id/tasks
POST /projects/sync
POST /runtime-images/:id([0-9a-fA-F-]{36})/adopt-local
POST /runtime-images/:id([0-9a-fA-F-]{36})/detect-local
POST /runtime-images/:id/official-digest
POST /runtime-images/import
POST /runtime-images/manual-digest
POST /runtime-images/registry/apply
POST /runtime-images/registry/pull
POST /runtime-images/registry/sync
POST /runtime-image-versions/:id/rescan
POST /runtime-image-versions/:id/status
POST /shared-assets/:id/archive
POST /skill-sources
POST /skill-sources/:id/sync
POST /skill-sources/:id/trust
POST /tasks/:canvasId/archive
POST /tasks/:canvasId/pause
POST /tasks/:canvasId/resume-session
POST /tasks/:canvasId/retry
POST /tasks/:canvasId/start
POST /tasks/:canvasId/unarchive
POST /tokens
POST /tokens/:id/revoke
POST /tokens/:id/rotate
POST /users
POST /users/:id/password
POST /webhooks/plane
PUT /gateway/*
PUT /projects/:id/integrations/plane
PUT /projects/:id/role-configs/:roleId
PUT /projects/:id/runtime-images/:imageId
PUT /role-configs/global/:roleId
`.trim().split(/\r?\n/);

export const OPENAPI_OPERATION_SURFACE = `
DELETE /agent-roles/{id}
DELETE /credentials/{id}
DELETE /projects/{id}/integrations/plane
DELETE /projects/{id}/role-configs/{roleId}
DELETE /skill-sources/{id}
GET /agent-roles
GET /audit-logs
GET /auth/me
GET /auth/status
GET /canvases/{id}
GET /canvases/{id}/broadcasts
GET /canvases/{id}/delta
GET /canvases/{id}/facts
GET /canvases/{id}/facts/{nodeId}
GET /canvases/{id}/nodes/{nodeId}
GET /canvases/{id}/report
GET /canvases/{id}/report/availability
GET /canvases/{id}/reports
GET /canvases/{id}/summary
GET /credentials
GET /credentials/{id}
GET /credentials/{id}/compatibility
GET /credentials/{id}/impact
GET /credentials/{id}/models
GET /credentials/providers
GET /findings
GET /canvases/{id}/messages
GET /findings/{id}
GET /findings/{id}/report
GET /findings/{id}/shared-assets
GET /global-settings
GET /health
GET /jobs
GET /jobs/{id}
GET /jobs/{id}/evidence
GET /jobs/{id}/evidence/session
GET /jobs/{id}/evidence/session/download
GET /jobs/{id}/evidence/stream
GET /metrics
GET /openapi.json
GET /plane-info
GET /platform/shared-assets
GET /projects
GET /projects/{id}
GET /projects/{id}/canvas
GET /projects/{id}/canvases
GET /projects/{id}/readiness
GET /projects/{id}/role-configs
GET /projects/{id}/roles
GET /projects/{id}/settings
GET /projects/{id}/shared-assets
GET /projects/{id}/shared-assets/policy
GET /readiness
GET /reports/{id}/markdown
GET /reports/{id}/sarif
GET /role-configs/bindable
GET /role-configs/global
PATCH /role-configs/{id}/agent-cli
PATCH /role-configs/{id}/runtime-image
GET /runtime-images
GET /runtime-images/{id}
GET /runtime-images/registry
GET /runtime-images/registry/pull-status
GET /runtime-image-versions/{id}/usage
GET /schema
GET /schema.md
GET /shared-assets/{id}/content
GET /skill-sources
GET /skill-sources/{id}
GET /tokens
PATCH /agent-roles/{id}
PATCH /canvases/{id}/facts/{nodeId}/verification
PATCH /credentials/{id}
PATCH /findings/{id}/verify-status
PATCH /global-settings
PATCH /jobs/{id}/priority
PATCH /projects/{id}
PATCH /projects/{id}/settings
PATCH /projects/{id}/shared-assets/policy
POST /agent-roles
POST /auth/bootstrap
POST /auth/change-password
POST /auth/change-username
POST /auth/login
POST /auth/logout
POST /canvases/{id}/report/retry
POST /canvases/{id}/report/refresh
POST /credentials
POST /credentials/{id}/models
POST /credentials/models/preview
POST /credentials/{id}/rotate
POST /credentials/{id}/status
POST /credentials/{id}/test
POST /credentials/batch-bind
POST /findings/{id}/report
POST /findings/{id}/shared-assets
POST /findings/{id}/evidence-jobs
POST /findings/{id}/verify
POST /canvases/{id}/messages
POST /jobs
POST /jobs/{id}/cancel
POST /platform/shared-assets
POST /jobs/{id}/resume
POST /jobs/{id}/rerun-current
POST /projects
POST /projects/{id}/archive
POST /projects/{id}/shared-assets
POST /projects/{id}/events
POST /projects/{id}/integrations/plane/sync
POST /projects/{id}/tasks
POST /runtime-images/{id}/adopt-local
POST /runtime-images/{id}/detect-local
POST /runtime-images/{id}/official-digest
POST /runtime-images/import
POST /runtime-images/manual-digest
PATCH /runtime-images/registry/channel
POST /runtime-images/registry/pull
POST /runtime-images/registry/sync
POST /runtime-image-versions/{id}/rescan
POST /runtime-image-versions/{id}/status
POST /shared-assets/{id}/archive
POST /skill-sources
POST /skill-sources/{id}/sync
POST /skill-sources/{id}/trust
POST /tasks/{canvasId}/pause
POST /tasks/{canvasId}/resume-session
POST /tasks/{canvasId}/retry
POST /tasks/{canvasId}/start
POST /tokens
POST /tokens/{id}/revoke
POST /tokens/{id}/rotate
POST /webhooks/plane
PUT /projects/{id}/integrations/plane
PUT /projects/{id}/role-configs/{roleId}
PUT /projects/{id}/runtime-images/{imageId}
PUT /role-configs/global/{roleId}
`.trim().split(/\r?\n/);
