import { isCurrentAgentCli, type CurrentAgentCli } from "@deepsonar/shared-types";
import { Eye, EyeSlash } from "@phosphor-icons/react";
import { useMemo, useState } from "react";
import type { Project, ProviderAccountCatalogItemView } from "./api";
import { CcSwitchClaudeFields } from "./CcSwitchClaudeFields";
import { CcSwitchCodexFields } from "./CcSwitchCodexFields";
import { CcSwitchOpenCodeFields } from "./CcSwitchOpenCodeFields";
import { formatJsonObject, validateJsonObjectText } from "./json-text";
import { SearchableSelect } from "./SearchableSelect";
import { validateTomlText } from "./toml-text";
import { type AgentCli, MASKED_SECRET_PLACEHOLDER, CONTEXT_WINDOW_TOKENS_MIN, CONTEXT_WINDOW_TOKENS_MAX, CREDENTIAL_CONCURRENCY_MAX, buildSettingsConfigFromEditor, defaultDshProviderYaml, extractBaseUrlFromSettingsClient, extractContextWindowTokens, extractModelsFromSettingsClient, extractModelIdFromSettings, extractSecretFromSettings, parseContextWindowTokens, parseCredentialConcurrency, parsePiSettingsText, providerProtocolLabel, validateDshYamlText } from "./credential-config-settings";

export type { AgentCli } from "./credential-config-settings";
export { MASKED_SECRET_PLACEHOLDER, CONTEXT_WINDOW_TOKENS_MIN, CONTEXT_WINDOW_TOKENS_MAX, CREDENTIAL_CONCURRENCY_MAX, buildSettingsConfigFromEditor, extractBaseUrlFromSettingsClient, extractContextWindowTokens, extractModelsFromSettingsClient, extractModelIdFromSettings, extractPiModelIdsFromSettings, extractProviderReasoning, extractSecretFromSettings, parseContextWindowTokens, parseCredentialConcurrency, parsePiSettingsText, patchProviderModelId, patchProviderModelIds, providerProtocolLabel, redactSecretText, redactSecretValues, restoreRedactedSecretText, restoreRedactedSecrets } from "./credential-config-settings";

export function CredentialConfigEditor({ mode, name, onNameChange, provider, onProviderChange, agentCli, onAgentCliChange, projectId, onProjectIdChange, projects, actorProjectId, providerCatalog, secret, onSecretChange, baseUrl, onBaseUrlChange, maxConcurrent, onMaxConcurrentChange, settingsJson, onSettingsJsonChange, tomlText, onTomlTextChange, authJson, onAuthJsonChange, contextWindowTokens, onContextWindowTokensChange, reasoning, onReasoningChange, modelOptions = [], onFetchModels, fetchingModels = false, canFetchModels = false, onNotice, onError, onSubmit, onCancel, busy = false, submitLabel }: {
  mode: "create" | "edit"; name: string; onNameChange: (v: string) => void; provider: string; onProviderChange: (v: string) => void; agentCli: AgentCli; onAgentCliChange: (v: CurrentAgentCli) => void; projectId: string; onProjectIdChange: (v: string) => void; projects: Project[]; actorProjectId: string | null; providerCatalog: ProviderAccountCatalogItemView[]; secret: string; onSecretChange: (v: string) => void; baseUrl: string; onBaseUrlChange: (v: string) => void; maxConcurrent: string; onMaxConcurrentChange: (v: string) => void; settingsJson: string; onSettingsJsonChange: (v: string) => void; tomlText: string; onTomlTextChange: (v: string) => void; authJson: string; onAuthJsonChange: (v: string) => void; contextWindowTokens: string; onContextWindowTokensChange: (v: string) => void; reasoning: string; onReasoningChange: (v: string) => void; modelOptions?: string[]; onFetchModels?: () => void; fetchingModels?: boolean; canFetchModels?: boolean; onNotice?: (v: string) => void; onError?: (v: string) => void; onSubmit: () => void; onCancel?: () => void; busy?: boolean; submitLabel?: string;
}) {
  const [showSecret, setShowSecret] = useState(false);
  const json = useMemo(() => validateJsonObjectText(settingsJson), [settingsJson]);
  const pi = useMemo(() => parsePiSettingsText(settingsJson), [settingsJson]);
  const dsh = useMemo(() => validateDshYamlText(settingsJson), [settingsJson]);
  const toml = useMemo(() => validateTomlText(tomlText), [tomlText]);
  const auth = useMemo(() => validateJsonObjectText(authJson), [authJson]);
  const contextValid = useMemo(() => { try { parseContextWindowTokens(contextWindowTokens); return true; } catch { return false; } }, [contextWindowTokens]);
  const concurrencyValid = useMemo(() => { try { parseCredentialConcurrency(maxConcurrent); return true; } catch { return false; } }, [maxConcurrent]);
  const compatible = providerCatalog.filter((item) => item.kind === "llm_provider" && item.compatible_agent_cli.includes(agentCli));
  const valid = (agentCli === "codex" ? toml.ok && auth.ok : agentCli === "dsh" ? dsh.ok : agentCli === "pi" ? pi.ok : json.ok) && contextValid && concurrencyValid;
  const configSecret = agentCli === "codex" && auth.ok && !auth.empty ? extractSecretFromSettings({ auth: auth.value }) : agentCli === "pi" && pi.ok && !pi.empty ? extractSecretFromSettings(pi.value) : json.ok && !json.empty ? extractSecretFromSettings(json.value) : "";
  const canSubmit = Boolean(provider && name.trim() && valid && (mode === "edit" || secret.trim() || configSecret));
  const switchCli = (next: AgentCli) => { if (!isCurrentAgentCli(next)) return; onAgentCliChange(next); const p = providerCatalog.find((item) => item.kind === "llm_provider" && item.compatible_agent_cli.includes(next))?.provider ?? provider; if (p !== provider) onProviderChange(p); onTomlTextChange(""); onAuthJsonChange(""); if (next === "claude-code") onSettingsJsonChange(formatJsonObject({ env: secret ? { ANTHROPIC_API_KEY: MASKED_SECRET_PLACEHOLDER, ANTHROPIC_AUTH_TOKEN: MASKED_SECRET_PLACEHOLDER } : {} })); else if (next === "pi") onSettingsJsonChange(formatJsonObject({ providers: { deepsonar: { baseUrl: baseUrl.trim(), api: p === "anthropic" ? "anthropic-messages" : "openai-responses", apiKey: secret ? MASKED_SECRET_PLACEHOLDER : "", models: [] } } })); else onSettingsJsonChange(defaultDshProviderYaml(p, baseUrl)); };
  return <div className="provider-flow-create credential-config-editor">
    <div className="provider-flow-create-grid"><SearchableSelect value={agentCli} onChange={(v) => switchCli(v as AgentCli)} options={[{ value: "claude-code", label: "Claude Code（settings.json）" }, { value: "pi", label: "Pi Coding Agent（models.json）" }, { value: "dsh", label: "DeepSeek Harness（JSON-RPC）" }]} placeholder="选择 Agent CLI" ariaLabel="Agent CLI 类型" clearable={false} /><SearchableSelect value={provider} onChange={onProviderChange} options={compatible.map((item) => ({ value: item.provider, label: providerProtocolLabel(item.provider, agentCli, providerCatalog) }))} placeholder="选择 Provider" ariaLabel="Provider" clearable={false} /></div>
    <div className="rounded-md border border-acc-400/20 bg-acc-400/[.04] px-3 py-3"><div className="mb-2 font-mono text-[10px] uppercase tracking-[0.14em] text-acc-300">Provider 连接与模型路由</div><div className="grid gap-3 sm:grid-cols-4"><label className="cc-switch-field"><span className="cc-switch-label">账号名称</span><input value={name} onChange={(e) => onNameChange(e.target.value)} className="theme-input-surface cc-switch-input" placeholder="team-provider" aria-label="账号名称" /></label><label className="cc-switch-field"><span className="cc-switch-label">Base URL</span><input value={baseUrl} onChange={(e) => onBaseUrlChange(e.target.value.trim().replace(/\/+$/u, ""))} className="theme-input-surface cc-switch-input" placeholder="https://api.example.com/v1" aria-label="Provider Base URL" /></label><label className="cc-switch-field"><span className="cc-switch-label">API Key</span><div className="relative"><input type={showSecret ? "text" : "password"} value={secret} onChange={(e) => onSecretChange(e.target.value)} className="theme-input-surface cc-switch-input w-full pr-10" autoComplete="off" aria-label="Provider API Key" /><button type="button" className="absolute right-1 top-1/2 -translate-y-1/2 !min-h-7 !px-2" onClick={() => setShowSecret((v) => !v)} aria-label={showSecret ? "隐藏 API Key" : "查看 API Key"}>{showSecret ? <EyeSlash size={16} /> : <Eye size={16} />}</button></div></label><label className="cc-switch-field"><span className="cc-switch-label">并发上限</span><input type="number" min={0} max={CREDENTIAL_CONCURRENCY_MAX} value={maxConcurrent} onChange={(e) => onMaxConcurrentChange(e.target.value)} className="theme-input-surface cc-switch-input" placeholder="不限制" aria-label="并发上限" aria-invalid={!concurrencyValid} /></label></div></div>
    <div className="hidden"><input value={projectId} onChange={(e) => onProjectIdChange(e.target.value)} /><span>{projects.length}{actorProjectId ?? ""}{contextWindowTokens}{reasoning}</span><input onChange={(e) => onContextWindowTokensChange(e.target.value)} /><input onChange={(e) => onReasoningChange(e.target.value)} /></div>
    <div className="rounded-md border border-white/[.08] bg-white/[.02] px-3 py-3"><div className="font-mono text-[10px] uppercase tracking-[0.14em] text-zinc-400">Agent 参数与容器配置</div><div className="mt-1 text-[12px] text-zinc-200">{agentCli === "claude-code" ? "Claude Code 将生成 .claude/settings.json" : agentCli === "pi" ? "Pi 将生成 .pi/agent/models.json" : "DSH 将生成运行配置文件"}</div></div>
    <details className="rounded-md border border-white/[.07] bg-black/10 px-3 py-2"><summary className="cursor-pointer text-[12px] text-zinc-300">高级：编辑 Agent 原生配置（可选）</summary><div className="mt-3">{agentCli === "claude-code" ? <CcSwitchClaudeFields settingsJson={settingsJson} onSettingsJsonChange={onSettingsJsonChange} apiKey={secret} onApiKeyChange={onSecretChange} baseUrl={baseUrl} onBaseUrlChange={onBaseUrlChange} showConnectionFields={false} onNotice={onNotice} onError={onError} /> : agentCli === "codex" ? <CcSwitchCodexFields authJson={authJson} onAuthJsonChange={onAuthJsonChange} tomlText={tomlText} onTomlTextChange={onTomlTextChange} apiKey={secret} onApiKeyChange={onSecretChange} baseUrl={baseUrl} onBaseUrlChange={onBaseUrlChange} showConnectionFields={false} showModelFields={false} modelOptions={modelOptions} onFetchModels={onFetchModels} fetchingModels={fetchingModels} canFetchModels={canFetchModels} onNotice={onNotice} onError={onError} /> : agentCli === "dsh" ? <label className="cc-switch-field"><span className="cc-switch-label">DSH Provider 配置 YAML</span><textarea value={settingsJson} onChange={(e) => onSettingsJsonChange(e.target.value)} rows={12} className="theme-input-surface cc-switch-json" spellCheck={false} /></label> : agentCli === "pi" ? <label className="cc-switch-field"><span className="cc-switch-label">Pi / llm-pi-ai 配置（YAML 或 JSON）</span><textarea value={settingsJson} onChange={(e) => onSettingsJsonChange(e.target.value)} rows={12} className="theme-input-surface cc-switch-json" spellCheck={false} /></label> : <CcSwitchOpenCodeFields settingsJson={settingsJson} onSettingsJsonChange={onSettingsJsonChange} apiKey={secret} onApiKeyChange={onSecretChange} baseUrl={baseUrl} onBaseUrlChange={onBaseUrlChange} showConnectionFields={false} showModelFields={false} provider={provider} modelOptions={modelOptions} onFetchModels={onFetchModels} fetchingModels={fetchingModels} canFetchModels={canFetchModels} onNotice={onNotice} onError={onError} />}</div></details>
    <div className="flex flex-wrap gap-2"><button type="button" onClick={onSubmit} disabled={busy || !canSubmit} className="provider-flow-apply" style={{ marginTop: 0, flex: 1 }}>{busy ? "保存中…" : (submitLabel ?? (mode === "create" ? "保存配置并添加账号" : "保存配置修改"))}</button>{onCancel && <button type="button" className="secondary-button" onClick={onCancel} disabled={busy}>取消</button>}</div>
  </div>;
}
