services:
  scheduler:
    environment:
      AGENT_MODE: real
    volumes:
      - blob_data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
  image-admission:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
