import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import test from "node:test";
import {
  OPENSANDBOX_EGRESS_IMAGE,
  OPENSANDBOX_EXECD_IMAGE,
  OPENSANDBOX_SERVER_IMAGE,
} from "./opensandbox-version.js";

const root = join(dirname(fileURLToPath(import.meta.url)), "../../..");

test("OpenSandbox deploy pins official schema and immutable digests", () => {
  const toml = readFileSync(join(root, "deploy/opensandbox/config.toml"), "utf8");
  const compose = readFileSync(join(root, "deploy/docker-compose.opensandbox.yml"), "utf8");
  assert.match(toml, /network_mode = "bridge"/);
  assert.match(toml, /no_new_privileges = true/);
  assert.match(toml, /drop_capabilities = \["ALL"\]/);
  assert.match(toml, /type = "sqlite"/);
  assert.match(toml, /mode = "direct"/);
  assert.doesNotMatch(toml, /(?:^|\s)latest(?:\s|$)|network_mode = "host"|api_key_env|^\s*driver\s*=/m);
  assert.match(toml, new RegExp(OPENSANDBOX_EXECD_IMAGE.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")));
  assert.match(toml, new RegExp(OPENSANDBOX_EGRESS_IMAGE.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")));
  assert.match(compose, new RegExp(OPENSANDBOX_SERVER_IMAGE.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")));
  assert.match(compose, /OPENSANDBOX_SERVER_API_KEY/);
  assert.match(compose, /driver: bridge/);
  assert.doesNotMatch(compose, /:latest|network_mode:\s*host/);
});

test("OpenSandbox production overlay is the default real deploy path", () => {
  const overlay = readFileSync(join(root, "deploy/docker-compose.opensandbox.prod.yml"), "utf8");
  const deploySh = readFileSync(join(root, "deploy/deploy.sh"), "utf8");
  const deployPs1 = readFileSync(join(root, "deploy/deploy.ps1"), "utf8");
  assert.match(overlay, new RegExp(OPENSANDBOX_SERVER_IMAGE.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")));
  assert.match(overlay, /SANDBOX_PROVIDER: opensandbox/);
  assert.match(overlay, /OPEN_SANDBOX_DOMAIN: \$\{OPEN_SANDBOX_DOMAIN:-opensandbox:8080\}/);
  assert.match(deploySh, /network connect bridge/);
  assert.match(overlay, /OPEN_SANDBOX_HOST_PORT:-18081/);
  assert.match(overlay, /condition: service_healthy/);
  assert.match(overlay, /127\.0\.0\.1:8080\/health/);
  assert.match(overlay, /OPENSANDBOX_SERVER_API_KEY/);
  assert.doesNotMatch(overlay, /:latest|network_mode:\s*host/);
  assert.doesNotMatch(overlay, /127\.0\.0\.1:8080:8080/);
  assert.match(deploySh, /SANDBOX_PROVIDER:-opensandbox/);
  assert.match(deploySh, /docker-compose.opensandbox.prod.yml/);
  assert.match(deploySh, /up\)[\s\S]*relax_bridge_forward/);
  assert.match(deploySh, /relax_bridge_forward[\s\S]*iptables-legacy -P FORWARD ACCEPT/);
  assert.match(deploySh, /down\/logs\/status\/check\/pull must not/);
  assert.match(deployPs1, /IsNullOrWhiteSpace\(\$env:SANDBOX_PROVIDER\)/);
  assert.match(deployPs1, /docker-compose.opensandbox.prod.yml/);
  const pkg = readFileSync(join(root, "package.json"), "utf8");
  const ci = readFileSync(join(root, ".github/workflows/ci.yml"), "utf8");
  assert.match(pkg, /ci:smoke:opensandbox-prod-stack/);
  assert.match(pkg, /ci:smoke:opensandbox-prod-compose": "pnpm --filter @deepsonar\/runtime-sandbox build/);
  assert.match(pkg, /ci:smoke:opensandbox-prod-official": "pnpm --filter @deepsonar\/runtime-sandbox build/);
  assert.match(pkg, /ci:smoke:opensandbox-reconcile": "pnpm --filter @deepsonar\/plane-client --filter @deepsonar\/runtime-sandbox build/);
  assert.match(pkg, /ci:smoke:opensandbox-reaper": "pnpm --filter @deepsonar\/plane-client --filter @deepsonar\/runtime-sandbox build/);
  assert.match(pkg, /ci:smoke:opensandbox-dispatch": "pnpm --filter @deepsonar\/plane-client --filter @deepsonar\/runtime-sandbox build/);
  assert.match(pkg, /ci:smoke:opensandbox-api": "pnpm --filter @deepsonar\/runtime-sandbox build/);
  assert.match(pkg, /ci:smoke:opensandbox-cli-control": "pnpm --filter @deepsonar\/runtime-sandbox build/);
  assert.match(pkg, /ci:smoke:opensandbox-gvisor": "pnpm --filter @deepsonar\/runtime-sandbox build/);
  assert.match(pkg, /ci:smoke:opensandbox-k8s-assets": "pnpm --filter @deepsonar\/runtime-sandbox build/);
  const isolate = readFileSync(join(root, "deploy/docker-compose.opensandbox.prod-isolated.yml"), "utf8");
  assert.match(isolate, /name: \$\{OPEN_SANDBOX_POC_GATEWAY_NET:-os-poc-sandbox-gateway\}/);
  assert.doesNotMatch(isolate, /^\s+name:\s*deepsonar-sandbox-gateway/m);
  const hostOverlay = readFileSync(join(root, "deploy/docker-compose.opensandbox.host.yml"), "utf8");
  assert.match(hostOverlay, /SANDBOX_PROVIDER: opensandbox/);
  assert.match(hostOverlay, /DEEPSONAR_GATEWAY_PROXY_UPSTREAM_URL: \$\{DEEPSONAR_GATEWAY_PROXY_UPSTREAM_URL:-http:\/\/host\.docker\.internal:\$\{SCHEDULER_HOST_PORT:-13100\}\/gateway\}/);
  assert.doesNotMatch(hostOverlay, /127\.0\.0\.1:13100\/gateway/);
  assert.match(hostOverlay, /DEEPSONAR_ADMIN_TOKEN: \$\{DEEPSONAR_ADMIN_TOKEN:\?set DEEPSONAR_ADMIN_TOKEN\}/);
  assert.doesNotMatch(hostOverlay, /poc-admin-token/);
  assert.match(hostOverlay, /OPEN_SANDBOX_DOMAIN: \$\{OPEN_SANDBOX_DOMAIN:-127\.0\.0\.1:8080\}/);
  assert.match(hostOverlay, /network_mode: host/);
  assert.match(hostOverlay, /host\.docker\.internal:host-gateway/);
  assert.match(hostOverlay, /BLOB_STORE: s3/);
  assert.match(hostOverlay, /127\.0\.0\.1:\$\{SILO_API_PORT:-19000\}/);
  assert.match(hostOverlay, /^\s+silo:/m);
  assert.match(hostOverlay, /^\s+silo-init:/m);
  assert.match(hostOverlay, /\/var\/run\/docker\.sock/);
  assert.match(hostOverlay, /Dockerfile\.scheduler/);
  assert.match(hostOverlay, /Dockerfile\.web/);
  assert.doesNotMatch(hostOverlay, /container_name:/);
  assert.match(ci, /OpenSandbox production compose merge/);
  assert.match(ci, /published: "18081"/);
  assert.match(ci, /OpenSandbox host overlay gateway upstream/);
  assert.match(ci, /host\.docker\.internal:14100\/gateway/);
  assert.match(ci, /127\.0\.0\.1:13100\/gateway/);
});

test("OpenSandbox Kubernetes overlay pins Kata BatchSandbox and official schema", () => {
  const toml = readFileSync(join(root, "deploy/opensandbox/config.k8s.toml"), "utf8");
  const template = readFileSync(join(root, "deploy/opensandbox/batchsandbox-template.yaml"), "utf8");
  const runtimeClass = readFileSync(join(root, "deploy/opensandbox/runtimeclass-kata.yaml"), "utf8");
  const namespace = readFileSync(join(root, "deploy/opensandbox/namespace.yaml"), "utf8");
  const quota = readFileSync(join(root, "deploy/opensandbox/resourcequota.yaml"), "utf8");
  const kustomization = readFileSync(join(root, "deploy/opensandbox/kustomization.yaml"), "utf8");
  assert.match(toml, /type = "kubernetes"/);
  assert.match(toml, /type = "kata"/);
  assert.match(toml, /k8s_runtime_class = "kata-qemu"/);
  assert.match(toml, /workload_provider = "batchsandbox"/);
  assert.match(toml, /namespace = "deepsonar-opensandbox"/);
  assert.match(toml, /mode = "direct"/);
  assert.doesNotMatch(toml, /(?:^|\s)latest(?:\s|$)|workload_provider = "agent-sandbox"|type = "gvisor"/m);
  assert.match(toml, new RegExp(OPENSANDBOX_EXECD_IMAGE.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")));
  assert.match(toml, new RegExp(OPENSANDBOX_EGRESS_IMAGE.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")));
  assert.match(template, /restartPolicy: Never/);
  assert.doesNotMatch(template, /^\s*runtimeClassName:/m);
  assert.match(runtimeClass, /name: kata-qemu/);
  assert.match(runtimeClass, /handler: kata-qemu/);
  assert.match(namespace, /name: deepsonar-opensandbox/);
  assert.match(quota, /kind: ResourceQuota/);
  assert.match(quota, /kind: LimitRange/);
  assert.match(quota, /namespace: deepsonar-opensandbox/);
  assert.match(quota, /pods: "32"/);
  assert.match(quota, /defaultRequest:/);
  assert.match(template, /requests:/);
  assert.match(template, /limits:/);
  assert.match(template, /drop: \["ALL"\]/);
  assert.match(template, /allowPrivilegeEscalation: false/);
  assert.match(kustomization, /namespace\.yaml/);
  assert.match(kustomization, /runtimeclass-kata\.yaml/);
  assert.match(kustomization, /resourcequota\.yaml/);
  assert.match(kustomization, /gateway-service\.yaml/);
  assert.doesNotMatch(kustomization, /batchsandbox-template\.yaml/);
  const gatewayService = readFileSync(join(root, "deploy/opensandbox/gateway-service.yaml"), "utf8");
  assert.match(gatewayService, /name: deepsonar-gateway-proxy/);
  assert.match(gatewayService, /port: 3100/);
  assert.match(gatewayService, /targetPort: 3100/);
  assert.doesNotMatch(gatewayService, /selector:/);
  assert.doesNotMatch(gatewayService, /port: 80/);
  const schedulerDockerfile = readFileSync(join(root, "deploy/Dockerfile.scheduler"), "utf8");
  assert.match(schedulerDockerfile, /KUBECTL_VERSION=v1\.36\.4/);
  assert.match(schedulerDockerfile, /\/usr\/local\/bin\/kubectl/);
  assert.match(schedulerDockerfile, /sha256sum -c/);
  const external = readFileSync(join(root, "deploy/opensandbox/config.k8s.external.toml"), "utf8");
  const k8sCompose = readFileSync(join(root, "deploy/docker-compose.opensandbox.k8s.yml"), "utf8");
  assert.match(external, /type = "kubernetes"/);
  assert.match(external, /type = "kata"/);
  assert.match(external, /k8s_runtime_class = "kata-qemu"/);
  assert.match(external, /kubeconfig_path = "\/etc\/opensandbox\/kubeconfig"/);
  assert.match(external, /port = 18084/);
  assert.doesNotMatch(external, /(?:^|\s)latest(?:\s|$)|workload_provider = "agent-sandbox"|type = "gvisor"/m);
  assert.match(k8sCompose, /config\.k8s\.external\.toml/);
  assert.match(k8sCompose, /OPEN_SANDBOX_KUBECONFIG/);
  assert.match(k8sCompose, /OPEN_SANDBOX_KUBERNETES=1/);
  assert.match(k8sCompose, /deepsonar-opensandbox-k8s/);
  assert.match(k8sCompose, /127\.0\.0\.1:18084\/health/);
  assert.doesNotMatch(k8sCompose, /docker\.sock|:latest/);
  assert.doesNotMatch(k8sCompose, /container_name: deepsonar-opensandbox$/m);
  const assetsPoc = readFileSync(join(root, "packages/runtime-sandbox/src/opensandbox-k8s-assets-poc.ts"), "utf8");
  const runtime = readFileSync(join(root, "apps/scheduler/src/runtime.ts"), "utf8");
  assert.match(assetsPoc, /OPEN_SANDBOX_POC_K8S_ASSETS/);
  assert.match(assetsPoc, /KubernetesSharedAssetsVolumeManager/);
  assert.match(assetsPoc, /sharedAssetsMount/);
  assert.match(assetsPoc, /OPENSANDBOX_POC_K8S_ASSETS_WRITABLE/);
  assert.match(assetsPoc, /OPENSANDBOX_POC_K8S_PVC_LEFTOVER/);
  assert.match(runtime, /KubernetesSharedAssetsVolumeManager/);
  assert.match(runtime, /OPEN_SANDBOX_KUBECONFIG/);
});

test("OpenSandbox vendor CLI PoC routes models through Scheduler Gateway", () => {
  const poc = readFileSync(join(root, "apps/scheduler/src/opensandbox-cli-control.poc.ts"), "utf8");
  assert.match(poc, /registerGateway/);
  assert.match(poc, /mintJobToken/);
  assert.match(poc, /encryptSecret/);
  assert.match(poc, /DEEPSONAR_GATEWAY_TOKEN/);
  assert.match(poc, /network: "restricted"/);
  assert.match(poc, /DEEPSONAR_ALLOW_EGRESS: "0"/);
  assert.doesNotMatch(poc, /network: "egress"/);
  assert.match(poc, /vendor key leaked into OpenSandbox worker env/);
  assert.match(poc, /vendor key leaked into OpenSandbox worker workspace/);
  assert.match(poc, /runtimeCliEnv/);
  assert.match(poc, /nudgesLeft/);
  assert.match(poc, /completion gate missing session/);
  assert.match(poc, /skillMaterializationPath/);
  assert.match(poc, /DEEPSONAR_CONTROL_SKILL/);
  assert.match(poc, /PLATFORM_SYSTEM_PROMPT/);
  assert.match(poc, /systemPromptPath/);
  assert.match(poc, /submit_hub_decision/);
  assert.match(poc, /for \(const selectedCli of selectedClis\)/);
  assert.match(poc, /vendor CLI PoC needs 0\.0\.0\.0:3100/);
  assert.match(poc, /vendor CLI E2E requires all current CLIs/);
  assert.match(poc, /vendor CLI E2E needs host docker access for Gateway bind/);
  assert.match(poc, /assertVendorUpstreamPayload/);
  assert.match(poc, /assertVendorUpstreamStatus/);
  assert.match(poc, /assertVendorOfficialOrigin/);
  assert.match(poc, /VENDOR_OFFICIAL_ORIGINS/);
  assert.match(poc, /VENDOR_UPSTREAM_NOT_JSON|assertVendorPlanReachable/);
  assert.match(poc, /180_000/);
  assert.match(poc, /CLI_SESSION_ADAPTERS/);
  assert.match(poc, /parseAgentSession/);
  assert.match(poc, /encodeSteer/);
  assert.match(poc, /adapter\.resume/);
  assert.match(poc, /adapter\.materialize/);
  assert.match(poc, /legacySettingsConfig/);
  assert.match(poc, /qualifyPiModelRef/);
  assert.match(poc, /encodeGetState/);
  assert.match(poc, /delete process\.env\.OPEN_SANDBOX_KUBERNETES/);
  assert.match(poc, /deepsonar-home/);
  assert.doesNotMatch(poc, /ANTHROPIC_API_KEY: vendorKey|ANTHROPIC_API_KEY: vendorSecret/);
  assert.doesNotMatch(poc, /OPENAI_API_KEY: vendorKey|DEEPSEEK_API_KEY: vendorKey/);
});

test("OpenSandbox live harness pins arch image separately from contract-fail busybox", () => {
  const harness = readFileSync(join(root, "agent-harness/test-opensandbox-poc.ts"), "utf8");
  assert.match(harness, /OPEN_SANDBOX_POC_ARCH_IMAGE/);
  assert.match(harness, /runOpenSandboxArchPoc/);
  assert.match(harness, /--case must be all, arch, images, prod-config, prod-up, k8s, or k8s-assets/);
  assert.match(harness, /runOpenSandboxOfficialImagesPoc/);
  assert.match(harness, /listOfficialOpenSandboxRuntimeImages/);
  assert.match(harness, /prod-config/);
  assert.match(harness, /prod-up/);
  assert.match(harness, /runOpenSandboxK8sPoc/);
  assert.match(harness, /runOpenSandboxK8sAssetsPoc/);
  assert.match(harness, /envClean/);
  assert.match(harness, /docker-compose.real.yml/);
  const k8sPoc = readFileSync(join(root, "packages/runtime-sandbox/src/opensandbox-k8s-poc.ts"), "utf8");
  const k8sGateway = readFileSync(join(root, "packages/runtime-sandbox/src/kubernetes-gateway.ts"), "utf8");
  const adapter = readFileSync(join(root, "packages/runtime-sandbox/src/opensandbox.ts"), "utf8");
  assert.match(k8sPoc, /OPENSANDBOX_POC_KATA_NETWORK_NOT_ISOLATED/);
  assert.match(k8sPoc, /OPENSANDBOX_POC_KATA_GATEWAY_BLOCKED/);
  assert.match(k8sPoc, /bindGatewayProxyToKubernetesService/);
  assert.match(k8sPoc, /http:\/\/\$\{GATEWAY_PROBE_SERVICE\}:3100\//);
  assert.match(k8sPoc, /name: gateway[\s\S]*port: 3100/);
  assert.match(k8sGateway, /OPENSANDBOX_POC_KATA_GATEWAY_SERVICE_IP/);
  assert.match(k8sGateway, /port: 3100/);
  assert.match(k8sGateway, /targetPort: 3100/);
  assert.doesNotMatch(k8sGateway, /port: 80/);
  assert.match(adapter, /\/etc\/hosts/);
  assert.match(adapter, /uid: GATEWAY_HOSTS_ROOT_UID/);
  assert.match(adapter, /GatewayHostsBindError/);
  assert.match(k8sPoc, /OPENSANDBOX_POC_KATA_DENY_LEAK/);
  assert.match(k8sPoc, /OPENSANDBOX_POC_KATA_HOST_ESCAPE/);
  assert.match(k8sPoc, /OPENSANDBOX_POC_KATA_ENV_LEAK/);
  assert.match(k8sPoc, /OPENSANDBOX_POC_KATA_HARD_LIMITS/);
  assert.match(k8sPoc, /OPENSANDBOX_POC_AGENT_SANDBOX_PRESENT/);
  const gvisorPoc = readFileSync(join(root, "packages/runtime-sandbox/src/opensandbox-gvisor-poc.ts"), "utf8");
  assert.match(gvisorPoc, /OPENSANDBOX_POC_GVISOR_EGRESS_UNEXPECTED/);
  assert.match(gvisorPoc, /Failed to initialize nft/);
  assert.match(gvisorPoc, /release\/20251006\/x86_64\/runsc/);
  assert.doesNotMatch(gvisorPoc, /storage\.googleapis\.com\/gvisor\/releases\/release\/latest/);
  assert.match(k8sPoc, /kubernetesResources: true/);
  assert.match(harness, /--project-directory/);
});

test("OpenSandbox adapter does not import Agentbox SDK types", () => {
  const adapter = readFileSync(join(root, "packages/runtime-sandbox/src/opensandbox.ts"), "utf8");
  const shared = readFileSync(join(root, "packages/runtime-sandbox/src/runtime-shared.ts"), "utf8");
  const agent = readFileSync(join(root, "packages/runtime-sandbox/src/runtime-agent.ts"), "utf8");
  const gateway = readFileSync(join(root, "packages/runtime-sandbox/src/runtime-gateway.ts"), "utf8");
  const docker = readFileSync(join(root, "packages/runtime-sandbox/src/runtime-docker.ts"), "utf8");
  assert.doesNotMatch(adapter, /from ["']\.\/agentbox\.js["']/);
  assert.doesNotMatch(adapter, /from ["']agentbox-sdk["']/);
  assert.doesNotMatch(agent, /from ["']\.\/agentbox\.js["']/);
  assert.doesNotMatch(agent, /from ["']agentbox-sdk["']/);
  assert.doesNotMatch(gateway, /from ["']\.\/agentbox\.js["']/);
  assert.doesNotMatch(gateway, /from ["']agentbox-sdk["']/);
  assert.doesNotMatch(docker, /from ["']\.\/agentbox\.js["']/);
  assert.doesNotMatch(docker, /from ["']agentbox-sdk["']/);
  assert.match(docker, /export async function readDockerWorkspaceFile/);
  assert.match(docker, /export async function writeDockerHumanInboxFile/);
  const assetsIntegration = readFileSync(join(root, "packages/runtime-sandbox/src/shared-assets-volume.integration.test.ts"), "utf8");
  assert.doesNotMatch(assetsIntegration, /from ["']\.\/agentbox\.js["']/);
  assert.match(assetsIntegration, /from ["']\.\/runtime-docker\.js["']/);
  assert.match(adapter, /from ["']\.\/runtime-shared\.js["']/);
  assert.match(adapter, /inspectPreparedSharedAssetsVolume/);
  assert.match(adapter, /assertSharedAssetsVolumeOwnership/);
  assert.match(agent, /export async function runRealAgent/);
  assert.match(shared, /export const SHARED_ASSETS_MOUNT_PATH/);
  assert.match(shared, /export function parseToolManifest/);
});

test("real runner is OpenSandbox only and Agentbox is deleted", () => {
  const barrel = readFileSync(join(root, "packages/runtime-sandbox/src/index.ts"), "utf8");
  const runtime = readFileSync(join(root, "apps/scheduler/src/runtime.ts"), "utf8");
  const pkg = JSON.parse(readFileSync(join(root, "packages/runtime-sandbox/package.json"), "utf8")) as {
    dependencies?: Record<string, string>;
    exports?: Record<string, { types?: string; default?: string }>;
  };
  assert.doesNotMatch(barrel, /from ["']\.\/agentbox\.js["']/);
  assert.doesNotMatch(barrel, /AgentboxRunner|createAgentboxRuntimeHost|wrapAgentboxProcess|agentbox-sdk/);
  assert.equal(pkg.exports?.["./agentbox"], undefined);
  assert.equal(pkg.dependencies?.["agentbox-sdk"], undefined);
  assert.doesNotMatch(runtime, /AgentboxRunner|runtime-sandbox\/agentbox/);
  assert.match(runtime, /provider !== ["']opensandbox["']/);
  assert.match(runtime, /kubernetesResources: config\.runtime\.openSandbox\.kubernetes/);
  assert.match(runtime, /KubernetesSharedAssetsVolumeManager/);
  assert.match(runtime, /bindGatewayProxyToKubernetesService/);
  const config = readFileSync(join(root, "apps/scheduler/src/config.ts"), "utf8");
  assert.match(config, /SANDBOX_PROVIDER", "opensandbox"/);
  assert.match(config, /OPEN_SANDBOX_KUBERNETES/);
});
